=== WGSL DUMP: RadixSortKernel1 (1989 lines) ===
// Kernel: RadixSortKernel1
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//
(null)
// Kernel: LauncherWrapper_110
// WorkgroupSize: 256
// SharedMemory: shared_0, shared_1
// Emulation: i64
(null)
(null)
// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}
(null)
// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}
(null)
// emu_i64/emu_u64 addition with carry
fn i64_add(a: emu_i64, b: emu_i64) -> emu_i64 {
    let lo = a.x + b.x;
    let carry = select(0u, 1u, lo < a.x);
    let hi = a.y + b.y + carry;
    return emu_i64(lo, hi);
}
(null)
// emu_i64 negation (two's complement)
fn i64_neg(a: emu_i64) -> emu_i64 {
    let inv = emu_i64(~a.x, ~a.y);
    return i64_add(inv, emu_i64(1u, 0u));
}
(null)
// emu_u64 multiplication (full 64x64 -> 64-bit result, ignoring overflow)
fn u64_mul(a: emu_u64, b: emu_u64) -> emu_u64 {
    // Split into 16-bit parts for WGSL compatibility
    let a_lo = a.x & 0xFFFFu;
    let a_hi = a.x >> 16u;
    let b_lo = b.x & 0xFFFFu;
    let b_hi = b.x >> 16u;
    
    // Partial products
    let p0 = a_lo * b_lo;
    let p1 = a_lo * b_hi;
    let p2 = a_hi * b_lo;
    let p3 = a_hi * b_hi;
    
    // Combine low parts
    let mid = (p0 >> 16u) + (p1 & 0xFFFFu) + (p2 & 0xFFFFu);
    let lo = (p0 & 0xFFFFu) | ((mid & 0xFFFFu) << 16u);
    
    // Combine high parts
    let hi = p3 + (p1 >> 16u) + (p2 >> 16u) + (mid >> 16u) + a.x * b.y + a.y * b.x;
    
    return emu_u64(lo, hi);
}
(null)
// emu_i64 multiplication (uses u64_mul internally)
fn i64_mul(a: emu_i64, b: emu_i64) -> emu_i64 {
    let neg_a = (a.y & 0x80000000u) != 0u;
    let neg_b = (b.y & 0x80000000u) != 0u;
    var abs_a = a;
    var abs_b = b;
    if (neg_a) { abs_a = i64_neg(a); }
    if (neg_b) { abs_b = i64_neg(b); }
    var result = u64_mul(abs_a, abs_b);
    if (neg_a != neg_b) { result = i64_neg(result); }
    return result;
}
(null)
// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}
(null)
// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}
(null)
// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}
(null)
// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}
(null)
(null)
// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);
(null)
struct struct_40 {
    field_0 : i32,
    field_1 : emu_i64,
    field_2 : i32,
};
(null)
// Param 0: Struct<View<Int32, Generic> [0], Int64 [8], Int8 [16]> (Element: Int32)
// Body struct field 0: View<Int32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param0_f0 : array<i32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 1: View<Int32, Generic> (Element: Int32)
@group(0) @binding(1) var<storage, read_write> param1 : array<i32>;
// Param 2: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// Param 3: Int32 (Element: Int32)
// -> Packed scalar at slot 1 (1 slots, type: i32)
// Param 4: Int32 (Element: Int32)
// -> Packed scalar at slot 2 (1 slots, type: i32)
// Param 5: Int32 (Element: Int32)
// -> Packed scalar at slot 3 (1 slots, type: i32)
// View offset for param1000 at scalar slot 4
// View offset for param1 at scalar slot 5
@group(0) @binding(2) var<storage, read> _scalar_params : array<u32>;
(null)
var<workgroup> shared_0 : array<i32, 1024>;
var<workgroup> shared_1 : array<i32, 2048>;
const workgroup_size : vec3<u32> = vec3<u32>(256u, 1u, 1u);
(null)
@compute @workgroup_size(256)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;
(null)
    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : i32 = 0;
    var v_2 : emu_i64 = emu_i64(0u, 0u);
    var v_3 : emu_i64 = emu_i64(0u, 0u);
    var v_4 : bool = false;
    var v_5 : emu_i64 = emu_i64(0u, 0u);
    var v_6 : emu_i64 = emu_i64(0u, 0u);
    var v_7 : bool = false;
    var v_8 : emu_i64 = emu_i64(0u, 0u);
    var v_9 : emu_i64 = emu_i64(0u, 0u);
    var v_10 : bool = false;
    var v_11 : i32 = 0;
    var v_12 : i32 = 0;
    var v_13 : bool = false;
    var v_14 : i32 = 0;
    var v_15 : bool = false;
    var v_16 : i32 = 0;
    var v_17 : i32 = 0;
    var v_18 : i32 = 0;
    var v_19 : i32 = 0;
    var v_20 : bool = false;
    var v_21 : bool = false;
    var v_22 : i32 = 0;
    var v_23 : bool = false;
    var v_24 : i32 = 0;
    var v_25 : i32 = 0;
    var v_26 : i32 = 0;
    var v_27 : i32 = 0;
    var v_28 : i32 = 0;
    var v_29 : i32 = 0;
    var v_30 : i32 = 0;
    var v_31 : i32 = 0;
    var v_32 : i32 = 0;
    var v_33 : i32 = 0;
    var v_34 : i32 = 0;
    var v_35 : i32 = 0;
    var v_36 : i32 = 0;
    var v_37 : i32 = 0;
    var v_38 : i32 = 0;
    var v_39 : emu_i64 = emu_i64(0u, 0u);
    var v_40 : bool = false;
    var v_41 : i32 = 0;
    var v_42 : bool = false;
    var v_43 : bool = false;
    var v_44 : bool = false;
    var v_45 : i32 = 0;
    var v_46 : i32 = 0;
    var v_47 : i32 = 0;
    var v_48 : i32 = 0;
    var v_49 : i32 = 0;
    var v_50 : i32 = 0;
    var v_51 : i32 = 0;
    var v_52 : bool = false;
    var v_53 : i32 = 0;
    var v_54 : bool = false;
    var v_55 : i32 = 0;
    var v_56 : i32 = 0;
    var v_57 : bool = false;
    var v_58 : i32 = 0;
    var v_59 : i32 = 0;
    var v_60 : bool = false;
    var v_61 : i32 = 0;
    var v_62 : i32 = 0;
    var v_63 : i32 = 0;
    var v_64 : i32 = 0;
    var v_65 : i32 = 0;
    var v_66 : i32 = 0;
    var v_67 : bool = false;
    var v_68 : i32 = 0;
    var v_69 : i32 = 0;
    var v_70 : i32 = 0;
    var v_71 : i32 = 0;
    var v_72 : bool = false;
    var v_73 : bool = false;
    var v_74 : bool = false;
    var v_75 : i32 = 0;
    var v_76 : i32 = 0;
    var v_77 : i32 = 0;
    var v_78 : i32 = 0;
    var v_79 : i32 = 0;
    var v_80 : i32 = 0;
    var v_81 : i32 = 0;
    var v_82 : i32 = 0;
    let v_83_f0 = &param0_f0;
    var v_83_f1 = i64_from_i32(i32(arrayLength(&param0_f0)));
    let v_84 = &param1;
    var v_86 = bitcast<i32>(_scalar_params[1]);
    var v_87 = bitcast<i32>(_scalar_params[2]);
    var v_88 = bitcast<i32>(_scalar_params[3]);
    var v_90 : i32;
    var v_91 : i32;
    var v_93 : i32;
    var v_94 : i32;
    var v_95 : i32;
    var v_96 : i32;
    var v_97 : i32;
    var v_98 : i32;
    var v_99 : i32;
    var v_100 : i32;
    var v_101 : i32;
    var v_105 : emu_i64;
    var v_107 : emu_i64;
    var v_112 : emu_i64;
    var v_114 : emu_i64;
    var v_119 : emu_i64;
    var v_121 : emu_i64;
    var v_123 : emu_i64;
    var v_125 : emu_i64;
    var v_127 : i32;
    var v_128 : i32;
    var v_129 : i32;
    var v_130 : i32;
    var v_131 : i32;
    var v_133 : i32;
    var v_134 : i32;
    var v_135 : i32;
    var v_136 : emu_i64;
    var v_138 : emu_i64;
    var v_140 : i32;
    var v_141 : i32;
    var v_142 : i32;
    var v_143 : i32;
    var v_144 : i32;
    var v_145 : i32;
    var v_146 : i32;
    var v_147 : i32;
    var v_148 : i32;
    var v_149 : i32;
    var v_150 : i32;
    var v_151 : i32;
    var v_152 : i32;
    var v_153 : i32;
    var v_154 : i32;
    var v_155 : i32;
    var v_156 : i32;
    var v_157 : i32;
    var v_158 : i32;
    var v_161 : i32;
    var v_164 : i32;
    var v_167 : i32;
    var v_168 : i32;
    var v_170 : i32;
    var v_172 : i32;
    var v_174 : i32;
    var v_176 : i32;
    var v_178 : i32;
    var v_179 : i32;
    var v_181 : i32;
    var v_182 : i32;
    var v_185 : i32;
    var v_186 : i32;
    var v_10000 : i32;
    var v_10001 : i32;
    var v_10002 : i32;
    var v_10004 : i32;
    var v_10005 : i32;
    var v_10006 : i32;
    var v_10007 : i32;
    var v_10008 : i32;
    var v_10012 : emu_i64;
    var v_10014 : emu_i64;
    var v_10018 : i32;
    var v_10020 : i32;
    var v_10028 : i32;
    var v_10029 : i32;
    var v_10030 : i32;
    var v_10031 : i32;
    var v_10032 : i32;
    var v_10033 : i32;
    var v_10039 : i32;
    var v_10040 : i32;
    var v_10041 : i32;
    var v_10042 : i32;
    var v_10048 : emu_i64;
    var v_10050 : emu_i64;
    var v_10057 : i32;
    var v_10060 : i32;
    var v_10062 : i32;
    var v_10064 : i32;
    var v_10066 : i32;
    var v_10067 : i32;
    var v_10068 : i32;
    var v_10074 : emu_i64;
    var v_10076 : emu_i64;
    var v_10079 : i32;
    var v_10080 : i32;
    var v_10082 : i32;
    var v_10083 : i32;
    var v_10086 : i32;
    var v_10087 : i32;
    var v_10090 : i32;
    var v_10091 : i32;
    var v_10092 : i32;
    var v_10093 : i32;
    var v_10094 : i32;
    var v_10095 : i32;
    var v_10099 : emu_i64;
    var v_10101 : emu_i64;
    var v_10105 : i32;
    var v_10107 : i32;
    var v_10114 : i32;
    var v_10117 : i32;
    var v_189 : i32;
    var v_190 : i32;
    var v_20000 : i32;
    var v_20001 : i32;
    var v_20002 : i32;
    var v_20004 : i32;
    var v_20005 : i32;
    var v_20006 : i32;
    var v_20007 : i32;
    var v_20008 : i32;
    var v_20012 : emu_i64;
    var v_20014 : emu_i64;
    var v_20018 : i32;
    var v_20020 : i32;
    var v_20028 : i32;
    var v_20029 : i32;
    var v_20030 : i32;
    var v_20031 : i32;
    var v_20032 : i32;
    var v_20033 : i32;
    var v_20039 : i32;
    var v_20040 : i32;
    var v_20041 : i32;
    var v_20042 : i32;
    var v_20048 : emu_i64;
    var v_20050 : emu_i64;
    var v_20057 : i32;
    var v_20060 : i32;
    var v_20062 : i32;
    var v_20064 : i32;
    var v_20066 : i32;
    var v_20067 : i32;
    var v_20068 : i32;
    var v_20074 : emu_i64;
    var v_20076 : emu_i64;
    var v_20079 : i32;
    var v_20080 : i32;
    var v_20082 : i32;
    var v_20083 : i32;
    var v_20086 : i32;
    var v_20087 : i32;
    var v_20090 : i32;
    var v_20091 : i32;
    var v_20092 : i32;
    var v_20093 : i32;
    var v_20094 : i32;
    var v_20095 : i32;
    var v_20099 : emu_i64;
    var v_20101 : emu_i64;
    var v_20105 : i32;
    var v_20107 : i32;
    var v_20114 : i32;
    var v_20117 : i32;
    var v_193 : i32;
    var v_194 : i32;
    var v_30000 : i32;
    var v_30001 : i32;
    var v_30002 : i32;
    var v_30004 : i32;
    var v_30005 : i32;
    var v_30006 : i32;
    var v_30007 : i32;
    var v_30008 : i32;
    var v_30012 : emu_i64;
    var v_30014 : emu_i64;
    var v_30018 : i32;
    var v_30020 : i32;
    var v_30028 : i32;
    var v_30029 : i32;
    var v_30030 : i32;
    var v_30031 : i32;
    var v_30032 : i32;
    var v_30033 : i32;
    var v_30039 : i32;
    var v_30040 : i32;
    var v_30041 : i32;
    var v_30042 : i32;
    var v_30048 : emu_i64;
    var v_30050 : emu_i64;
    var v_30057 : i32;
    var v_30060 : i32;
    var v_30062 : i32;
    var v_30064 : i32;
    var v_30066 : i32;
    var v_30067 : i32;
    var v_30068 : i32;
    var v_30074 : emu_i64;
    var v_30076 : emu_i64;
    var v_30079 : i32;
    var v_30080 : i32;
    var v_30082 : i32;
    var v_30083 : i32;
    var v_30086 : i32;
    var v_30087 : i32;
    var v_30090 : i32;
    var v_30091 : i32;
    var v_30092 : i32;
    var v_30093 : i32;
    var v_30094 : i32;
    var v_30095 : i32;
    var v_30099 : emu_i64;
    var v_30101 : emu_i64;
    var v_30105 : i32;
    var v_30107 : i32;
    var v_30114 : i32;
    var v_30117 : i32;
    var v_197 : i32;
    var v_198 : i32;
    var v_40000 : i32;
    var v_40001 : i32;
    var v_40002 : i32;
    var v_40004 : i32;
    var v_40005 : i32;
    var v_40006 : i32;
    var v_40007 : i32;
    var v_40008 : i32;
    var v_40012 : emu_i64;
    var v_40014 : emu_i64;
    var v_40018 : i32;
    var v_40020 : i32;
    var v_40028 : i32;
    var v_40029 : i32;
    var v_40030 : i32;
    var v_40031 : i32;
    var v_40032 : i32;
    var v_40033 : i32;
    var v_40039 : i32;
    var v_40040 : i32;
    var v_40041 : i32;
    var v_40042 : i32;
    var v_40048 : emu_i64;
    var v_40050 : emu_i64;
    var v_40057 : i32;
    var v_40060 : i32;
    var v_40062 : i32;
    var v_40064 : i32;
    var v_40066 : i32;
    var v_40067 : i32;
    var v_40068 : i32;
    var v_40074 : emu_i64;
    var v_40076 : emu_i64;
    var v_40079 : i32;
    var v_40080 : i32;
    var v_40082 : i32;
    var v_40083 : i32;
    var v_40086 : i32;
    var v_40087 : i32;
    var v_40090 : i32;
    var v_40091 : i32;
    var v_40092 : i32;
    var v_40093 : i32;
    var v_40094 : i32;
    var v_40095 : i32;
    var v_40099 : emu_i64;
    var v_40101 : emu_i64;
    var v_40105 : i32;
    var v_40107 : i32;
    var v_40114 : i32;
    var v_40117 : i32;
    var v_199 : i32;
    var v_200 : i32;
    var v_202 : i32;
    var v_204 : i32;
    var v_205 : i32;
    var v_206 : i32;
    var v_208 : i32;
    var v_209 : i32;
    var v_211 : i32;
    var v_213 : i32;
    var v_214 : i32;
    var v_215 : i32;
    var v_217 : i32;
    var v_218 : i32;
    var v_220 : i32;
    var v_222 : i32;
    var v_223 : i32;
    var v_224 : i32;
    var v_226 : i32;
    var v_228 : i32;
    var v_230 : i32;
    var v_231 : i32;
    var v_232 : i32;
    var v_234 : i32;
    var v_235 : i32;
    var v_236 : i32;
    var v_237 : i32;
    var v_239 : i32;
    var v_240 : i32;
    var v_241 : i32;
    var v_242 : i32;
    var v_244 : i32;
    var v_245 : i32;
    var v_247 : i32;
    var v_248 : i32;
    var v_250 : i32;
    var v_251 : i32;
    var v_252 : i32;
    var v_253 : i32;
    var v_255 : i32;
    var v_258 : i32;
    var v_261 : i32;
    var v_102 : emu_i64;
    var v_103 : emu_i64;
    var v_104 : emu_i64;
    var v_106 : bool;
    var v_108 : bool;
    var v_109 : emu_i64;
    var v_110 : emu_i64;
    var v_111 : emu_i64;
    var v_113 : bool;
    var v_115 : bool;
    var v_116 : emu_i64;
    var v_117 : emu_i64;
    var v_118 : emu_i64;
    var v_120 : bool;
    var v_122 : bool;
    var v_124 : bool;
    var v_126 : bool;
    var v_132 : bool;
    var v_137 : bool;
    var v_139 : bool;
    var v_159 : bool;
    var v_160 : bool;
    var v_162 : bool;
    var v_163 : bool;
    var v_165 : bool;
    var v_177 : bool;
    var v_10009 : vec2<u32>;
    var v_10010 : vec2<u32>;
    var v_10011 : vec2<u32>;
    var v_10013 : bool;
    var v_10015 : bool;
    var v_10016 : bool;
    var v_10017 : i32;
    var v_10019 : bool;
    var v_10021 : bool;
    var v_10022 : bool;
    var v_10023 : i32;
    var v_10024 : i32;
    var v_10025 : i32;
    var v_10026 : i32;
    var v_10034 : bool;
    var v_10035 : bool;
    var v_10036 : bool;
    var v_10037 : bool;
    var v_10038 : bool;
    var v_10043 : vec2<u32>;
    var v_10044 : vec2<u32>;
    var v_10045 : vec2<u32>;
    var v_10046 : vec2<u32>;
    var v_10047 : vec2<u32>;
    var v_10049 : bool;
    var v_10051 : bool;
    var v_10052 : bool;
    var v_10053 : i32;
    var v_10054 : i32;
    var v_10055 : bool;
    var v_10058 : i32;
    var v_10063 : i32;
    var v_10065 : i32;
    var v_10069 : vec2<u32>;
    var v_10070 : vec2<u32>;
    var v_10071 : vec2<u32>;
    var v_10072 : vec2<u32>;
    var v_10073 : vec2<u32>;
    var v_10075 : bool;
    var v_10077 : bool;
    var v_10078 : bool;
    var v_10081 : bool;
    var v_10084 : bool;
    var v_10085 : bool;
    var v_10088 : bool;
    var v_10089 : bool;
    var v_10096 : vec2<u32>;
    var v_10097 : vec2<u32>;
    var v_10098 : vec2<u32>;
    var v_10100 : bool;
    var v_10102 : bool;
    var v_10103 : bool;
    var v_10104 : i32;
    var v_10106 : bool;
    var v_10108 : bool;
    var v_10109 : bool;
    var v_10110 : i32;
    var v_10111 : i32;
    var v_10112 : i32;
    var v_10113 : i32;
    var v_10115 : i32;
    var v_20009 : vec2<u32>;
    var v_20010 : vec2<u32>;
    var v_20011 : vec2<u32>;
    var v_20013 : bool;
    var v_20015 : bool;
    var v_20016 : bool;
    var v_20017 : i32;
    var v_20019 : bool;
    var v_20021 : bool;
    var v_20022 : bool;
    var v_20023 : i32;
    var v_20024 : i32;
    var v_20025 : i32;
    var v_20026 : i32;
    var v_20034 : bool;
    var v_20035 : bool;
    var v_20036 : bool;
    var v_20037 : bool;
    var v_20038 : bool;
    var v_20043 : vec2<u32>;
    var v_20044 : vec2<u32>;
    var v_20045 : vec2<u32>;
    var v_20046 : vec2<u32>;
    var v_20047 : vec2<u32>;
    var v_20049 : bool;
    var v_20051 : bool;
    var v_20052 : bool;
    var v_20053 : i32;
    var v_20054 : i32;
    var v_20055 : bool;
    var v_20058 : i32;
    var v_20063 : i32;
    var v_20065 : i32;
    var v_20069 : vec2<u32>;
    var v_20070 : vec2<u32>;
    var v_20071 : vec2<u32>;
    var v_20072 : vec2<u32>;
    var v_20073 : vec2<u32>;
    var v_20075 : bool;
    var v_20077 : bool;
    var v_20078 : bool;
    var v_20081 : bool;
    var v_20084 : bool;
    var v_20085 : bool;
    var v_20088 : bool;
    var v_20089 : bool;
    var v_20096 : vec2<u32>;
    var v_20097 : vec2<u32>;
    var v_20098 : vec2<u32>;
    var v_20100 : bool;
    var v_20102 : bool;
    var v_20103 : bool;
    var v_20104 : i32;
    var v_20106 : bool;
    var v_20108 : bool;
    var v_20109 : bool;
    var v_20110 : i32;
    var v_20111 : i32;
    var v_20112 : i32;
    var v_20113 : i32;
    var v_20115 : i32;
    var v_30009 : vec2<u32>;
    var v_30010 : vec2<u32>;
    var v_30011 : vec2<u32>;
    var v_30013 : bool;
    var v_30015 : bool;
    var v_30016 : bool;
    var v_30017 : i32;
    var v_30019 : bool;
    var v_30021 : bool;
    var v_30022 : bool;
    var v_30023 : i32;
    var v_30024 : i32;
    var v_30025 : i32;
    var v_30026 : i32;
    var v_30034 : bool;
    var v_30035 : bool;
    var v_30036 : bool;
    var v_30037 : bool;
    var v_30038 : bool;
    var v_30043 : vec2<u32>;
    var v_30044 : vec2<u32>;
    var v_30045 : vec2<u32>;
    var v_30046 : vec2<u32>;
    var v_30047 : vec2<u32>;
    var v_30049 : bool;
    var v_30051 : bool;
    var v_30052 : bool;
    var v_30053 : i32;
    var v_30054 : i32;
    var v_30055 : bool;
    var v_30058 : i32;
    var v_30063 : i32;
    var v_30065 : i32;
    var v_30069 : vec2<u32>;
    var v_30070 : vec2<u32>;
    var v_30071 : vec2<u32>;
    var v_30072 : vec2<u32>;
    var v_30073 : vec2<u32>;
    var v_30075 : bool;
    var v_30077 : bool;
    var v_30078 : bool;
    var v_30081 : bool;
    var v_30084 : bool;
    var v_30085 : bool;
    var v_30088 : bool;
    var v_30089 : bool;
    var v_30096 : vec2<u32>;
    var v_30097 : vec2<u32>;
    var v_30098 : vec2<u32>;
    var v_30100 : bool;
    var v_30102 : bool;
    var v_30103 : bool;
    var v_30104 : i32;
    var v_30106 : bool;
    var v_30108 : bool;
    var v_30109 : bool;
    var v_30110 : i32;
    var v_30111 : i32;
    var v_30112 : i32;
    var v_30113 : i32;
    var v_30115 : i32;
    var v_40009 : emu_i64;
    var v_40010 : emu_i64;
    var v_40011 : emu_i64;
    var v_40013 : bool;
    var v_40015 : bool;
    var v_40016 : bool;
    var v_40017 : i32;
    var v_40019 : bool;
    var v_40021 : bool;
    var v_40022 : bool;
    var v_40023 : i32;
    var v_40024 : i32;
    var v_40025 : i32;
    var v_40026 : i32;
    var v_40034 : bool;
    var v_40035 : bool;
    var v_40036 : bool;
    var v_40037 : bool;
    var v_40038 : bool;
    var v_40043 : emu_i64;
    var v_40044 : emu_i64;
    var v_40045 : emu_i64;
    var v_40046 : emu_i64;
    var v_40047 : emu_i64;
    var v_40049 : bool;
    var v_40051 : bool;
    var v_40052 : bool;
    var v_40053 : i32;
    var v_40054 : i32;
    var v_40055 : bool;
    var v_40058 : i32;
    var v_40063 : i32;
    var v_40065 : i32;
    var v_40069 : emu_i64;
    var v_40070 : emu_i64;
    var v_40071 : emu_i64;
    var v_40072 : emu_i64;
    var v_40073 : emu_i64;
    var v_40075 : bool;
    var v_40077 : bool;
    var v_40078 : bool;
    var v_40081 : bool;
    var v_40084 : bool;
    var v_40085 : bool;
    var v_40088 : bool;
    var v_40089 : bool;
    var v_40096 : emu_i64;
    var v_40097 : emu_i64;
    var v_40098 : emu_i64;
    var v_40100 : bool;
    var v_40102 : bool;
    var v_40103 : bool;
    var v_40104 : i32;
    var v_40106 : bool;
    var v_40108 : bool;
    var v_40109 : bool;
    var v_40110 : i32;
    var v_40111 : i32;
    var v_40112 : i32;
    var v_40113 : i32;
    var v_40115 : i32;
    var v_203 : bool;
    var v_212 : bool;
    var v_221 : bool;
    var v_229 : bool;
    var v_243 : bool;
    var v_249 : bool;
    var v_254 : bool;
    var v_256 : bool;
    var v_257 : bool;
    var v_259 : bool;
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
    let v_89 = v_83_f0;
    let v_92 = &shared_0;
    let v_10003 = &shared_1;
    let v_20003 = &shared_1;
    let v_30003 = &shared_1;
    let v_40003 = &shared_1;
(null)
    v_0 = v_83_f1;
    v_90 = i32(256);
    v_91 = i32(1024);
(null)
    v_1 = i32(group_id.x + group_id.y * num_workgroups.x);
    v_93 = i32(group_id.x + group_id.y * num_workgroups.x);
    v_94 = i32(group_id.y);
    v_95 = i32(group_id.z);
    v_96 = i32(local_id.x);
    v_97 = i32(local_id.y);
    v_98 = i32(local_id.z);
    v_99 = i32(workgroup_size.x);
    v_100 = i32(workgroup_size.y);
    v_101 = i32(workgroup_size.z);
    v_102 = i64_from_i32(v_96);
    v_103 = i64_from_i32(v_93);
    v_104 = i64_from_i32(v_99);
    v_2 = i64_mul(v_103, v_104);
    v_3 = i64_add(v_102, v_2);
    v_105 = _c_i64_0;
    v_106 = i64_ge(v_3, v_105);
    v_107 = _c_i64_1;
    v_108 = i64_le(v_3, v_107);
    v_4 = v_106 & v_108;
    v_109 = i64_from_i32(v_97);
    v_110 = i64_from_i32(v_94);
    v_111 = i64_from_i32(v_100);
    v_5 = i64_mul(v_110, v_111);
    v_6 = i64_add(v_109, v_5);
    v_112 = _c_i64_0;
    v_113 = i64_ge(v_6, v_112);
    v_114 = _c_i64_1;
    v_115 = i64_le(v_6, v_114);
    v_7 = v_113 & v_115;
    v_116 = i64_from_i32(v_98);
    v_117 = i64_from_i32(v_95);
    v_118 = i64_from_i32(v_101);
    v_8 = i64_mul(v_117, v_118);
    v_9 = i64_add(v_116, v_8);
    v_119 = _c_i64_0;
    v_120 = i64_ge(v_9, v_119);
    v_121 = _c_i64_1;
    v_122 = i64_le(v_9, v_121);
    v_10 = v_120 & v_122;
    v_11 = v_93 * v_99;
    v_12 = v_96 + v_11;
    v_123 = _c_i64_0;
    v_124 = i64_ge(v_0, v_123);
    v_125 = _c_i64_1;
    v_126 = i64_le(v_0, v_125);
    v_13 = v_124 & v_126;
    v_14 = i64_to_i32(v_0);
    v_127 = i32(0);
    v_15 = v_14 == v_127;
    v_16 = i32(3);
    v_128 = i32(31);
    v_17 = v_88 & v_128;
    v_129 = i32(local_id.x);
    v_130 = i32(workgroup_size.x);
    v_131 = i32(1);
    v_18 = v_130 - v_131;
    v_132 = v_129 != v_18;
    v_133 = i32(local_id.x);
    v_134 = i32(workgroup_size.x);
    v_135 = i32(1);
    v_19 = v_134 - v_135;
    v_20 = v_133 == v_19;
    v_136 = _c_i64_0;
    v_137 = i64_ge(v_0, v_136);
    v_138 = _c_i64_1;
    v_139 = i64_le(v_0, v_138);
    v_21 = v_137 & v_139;
    v_22 = i64_to_i32(v_0);
    v_140 = i32(0);
    v_23 = v_22 == v_140;
    v_141 = i32(num_workgroups.x * num_workgroups.y);
    v_142 = i32(workgroup_size.x);
    v_24 = v_141 * v_142;
    v_143 = i32(local_id.x);
    v_25 = v_143 + v_90;
    v_144 = i32(local_id.x);
    v_145 = i32(512);
    v_26 = v_144 + v_145;
    v_146 = i32(local_id.x);
    v_147 = i32(768);
    v_27 = v_146 + v_147;
    v_148 = i32(local_id.x);
    v_28 = v_148 + v_90;
    v_149 = i32(local_id.x);
    v_150 = i32(512);
    v_29 = v_149 + v_150;
    v_151 = i32(local_id.x);
    v_152 = i32(768);
    v_30 = v_151 + v_152;
    v_153 = i32(local_id.x);
    v_31 = v_153 + v_90;
    v_154 = i32(local_id.x);
    v_155 = i32(512);
    v_32 = v_154 + v_155;
    v_156 = i32(1);
    v_33 = v_86 << u32(v_156);
    v_34 = i32(3);
    v_157 = i32(local_id.x);
    v_158 = i32(768);
    v_35 = v_157 + v_158;
    v_36 = v_86 * v_34;
    v_37 = v_1;
    v_38 = v_12;
    loop {
        v_159 = v_38 < v_87;
        let _uf_break_v_159 = (v_37 * i32(workgroup_size.x)) < v_87;
        if (!_uf_break_v_159) {
            break;
        }
        v_39 = i64_from_i32(v_38);
        v_40 = i64_lt(v_39, v_0);
        v_41 = i32(0);
        v_160 = i64_ge(v_39, v_0);
        if (!v_160) {
            v_161 = i32(0);
            v_162 = v_38 >= v_161;
            v_163 = v_38 < v_14;
            v_42 = v_162 & v_163;
            v_164 = i32(0);
            v_165 = v_38 == v_164;
            v_43 = v_165 & v_15;
            v_44 = v_42 | v_43;
            let v_166 = &param0_f0[(i32(_scalar_params[4]) + v_38)];
            v_45 = *v_166;
            v_46 = v_45;
        } else {
            v_46 = v_41;
        }
        v_167 = i32(-2147483648);
        v_47 = v_46 ^ v_167;
        v_48 = v_47 >> u32(v_17);
        v_49 = v_48 & v_16;
        v_168 = i32(local_id.x);
        let v_169 = &v_92[v_168];
        v_170 = i32(0);
        *v_169 = v_170;
        let v_171 = &v_92[v_25];
        v_172 = i32(0);
        *v_171 = v_172;
        let v_173 = &v_92[v_26];
        v_174 = i32(0);
        *v_173 = v_174;
        let v_175 = &v_92[v_27];
        v_176 = i32(0);
        *v_175 = v_176;
        v_177 = i64_ge(v_39, v_0);
        if (!v_177) {
            v_178 = i32(local_id.x);
            v_179 = i32(8);
            v_50 = v_49 << u32(v_179);
            v_51 = v_178 + v_50;
            let v_180 = &v_92[v_51];
            v_181 = i32(1);
            *v_180 = v_181;
        } else {
        }
        workgroupBarrier();
        storageBarrier();
        v_182 = i32(local_id.x);
        let v_183 = &v_92[v_182];
        let v_184 = &v_92[v_182];
        v_185 = *v_184;
        // --- BEGIN inlined helper: ExclusiveScan_115 ---
        {
        v_10002 = i32(2048);
(null)
        v_10004 = i32(local_id.x);
        v_10005 = i32(local_id.y);
        v_10006 = i32(local_id.z);
        v_10007 = i32(workgroup_size.x);
        v_10008 = i32(workgroup_size.y);
        v_10009 = i64_from_i32(v_10007);
        v_10010 = i64_from_i32(v_10008);
        v_10011 = i64_mul(v_10009, v_10010);
        v_10012 = _c_i64_0;
        v_10013 = i64_ge(v_10011, v_10012);
        v_10014 = _c_i64_1;
        v_10015 = i64_le(v_10011, v_10014);
        v_10016 = v_10013 & v_10015;
        v_10017 = v_10007 * v_10008;
        v_10018 = i32(1);
        v_10019 = v_10007 >= v_10018;
        v_10020 = i32(1);
        v_10021 = v_10017 >= v_10020;
        v_10022 = v_10017 >= v_10007;
        v_10023 = v_10005 * v_10007;
        v_10024 = v_10004 + v_10023;
        v_10025 = v_10006 * v_10017;
        v_10026 = v_10024 + v_10025;
        let v_10027 = &v_10003[v_10026];
        *v_10027 = v_185;
        workgroupBarrier();
        storageBarrier();
        v_10028 = i32(local_id.x);
        v_10029 = i32(0);
        v_10030 = i32(local_id.y);
        v_10031 = i32(0);
        v_10032 = i32(local_id.z);
        v_10033 = i32(0);
        v_10034 = v_10028 != v_10029;
        v_10035 = v_10030 != v_10031;
        v_10036 = v_10034 | v_10035;
        v_10037 = v_10032 != v_10033;
        v_10038 = v_10036 | v_10037;
        if (v_10038) {
        } else {
            v_10039 = i32(1);
            v_10040 = i32(workgroup_size.x);
            v_10041 = i32(workgroup_size.y);
            v_10042 = i32(workgroup_size.z);
            v_10043 = i64_from_i32(v_10040);
            v_10044 = i64_from_i32(v_10041);
            v_10045 = i64_mul(v_10043, v_10044);
            v_10046 = i64_from_i32(v_10042);
            v_10047 = i64_mul(v_10045, v_10046);
            v_10048 = _c_i64_0;
            v_10049 = i64_ge(v_10047, v_10048);
            v_10050 = _c_i64_1;
            v_10051 = i64_le(v_10047, v_10050);
            v_10052 = v_10049 & v_10051;
            v_10053 = v_10040 * v_10041;
            v_10054 = v_10053 * v_10042;
            v_10000 = v_10039;
            loop {
                v_10055 = v_10000 < v_10054;
                if (!v_10055) { break; }
                let v_10056 = &v_10003[v_10000];
                v_10057 = i32(1);
                v_10058 = v_10000 - v_10057;
                let v_10059 = &v_10003[v_10058];
                v_10060 = *v_10059;
                let v_10061 = &v_10003[v_10000];
                v_10062 = *v_10061;
                v_10063 = v_10060 + v_10062;
                *v_10056 = v_10063;
                v_10064 = i32(1);
                v_10065 = v_10000 + v_10064;
                v_10000 = v_10065;
                // loop continue (back-edge)
            }
        }
        workgroupBarrier();
        storageBarrier();
        v_10066 = i32(workgroup_size.x);
        v_10067 = i32(workgroup_size.y);
        v_10068 = i32(workgroup_size.z);
        v_10069 = i64_from_i32(v_10066);
        v_10070 = i64_from_i32(v_10067);
        v_10071 = i64_mul(v_10069, v_10070);
        v_10072 = i64_from_i32(v_10068);
        v_10073 = i64_mul(v_10071, v_10072);
        v_10074 = _c_i64_0;
        v_10075 = i64_ge(v_10073, v_10074);
        v_10076 = _c_i64_1;
        v_10077 = i64_le(v_10073, v_10076);
        v_10078 = v_10075 & v_10077;
        v_10079 = i32(local_id.x);
        v_10080 = i32(0);
        v_10081 = v_10079 == v_10080;
        v_10082 = i32(local_id.y);
        v_10083 = i32(0);
        v_10084 = v_10082 == v_10083;
        v_10085 = v_10081 & v_10084;
        v_10086 = i32(local_id.z);
        v_10087 = i32(0);
        v_10088 = v_10086 == v_10087;
        v_10089 = v_10085 & v_10088;
        if (v_10089) {
            v_10090 = i32(0);
            v_10001 = v_10090;
        } else {
            v_10091 = i32(local_id.x);
            v_10092 = i32(local_id.y);
            v_10093 = i32(local_id.z);
            v_10094 = i32(workgroup_size.x);
            v_10095 = i32(workgroup_size.y);
            v_10096 = i64_from_i32(v_10094);
            v_10097 = i64_from_i32(v_10095);
            v_10098 = i64_mul(v_10096, v_10097);
            v_10099 = _c_i64_0;
            v_10100 = i64_ge(v_10098, v_10099);
            v_10101 = _c_i64_1;
            v_10102 = i64_le(v_10098, v_10101);
            v_10103 = v_10100 & v_10102;
            v_10104 = v_10094 * v_10095;
            v_10105 = i32(1);
            v_10106 = v_10094 >= v_10105;
            v_10107 = i32(1);
            v_10108 = v_10104 >= v_10107;
            v_10109 = v_10104 >= v_10094;
            v_10110 = v_10092 * v_10094;
            v_10111 = v_10091 + v_10110;
            v_10112 = v_10093 * v_10104;
            v_10113 = v_10111 + v_10112;
            v_10114 = i32(1);
            v_10115 = v_10113 - v_10114;
            let v_10116 = &v_10003[v_10115];
            v_10117 = *v_10116;
            v_10001 = v_10117;
        }
        v_186 = v_10001;
        }
        // --- END inlined helper: ExclusiveScan_115 ---
        *v_183 = v_186;
        let v_187 = &v_92[v_28];
        let v_188 = &v_92[v_28];
        v_189 = *v_188;
        // --- BEGIN inlined helper: ExclusiveScan_115 ---
        {
        v_20002 = i32(2048);
(null)
        v_20004 = i32(local_id.x);
        v_20005 = i32(local_id.y);
        v_20006 = i32(local_id.z);
        v_20007 = i32(workgroup_size.x);
        v_20008 = i32(workgroup_size.y);
        v_20009 = i64_from_i32(v_20007);
        v_20010 = i64_from_i32(v_20008);
        v_20011 = i64_mul(v_20009, v_20010);
        v_20012 = _c_i64_0;
        v_20013 = i64_ge(v_20011, v_20012);
        v_20014 = _c_i64_1;
        v_20015 = i64_le(v_20011, v_20014);
        v_20016 = v_20013 & v_20015;
        v_20017 = v_20007 * v_20008;
        v_20018 = i32(1);
        v_20019 = v_20007 >= v_20018;
        v_20020 = i32(1);
        v_20021 = v_20017 >= v_20020;
        v_20022 = v_20017 >= v_20007;
        v_20023 = v_20005 * v_20007;
        v_20024 = v_20004 + v_20023;
        v_20025 = v_20006 * v_20017;
        v_20026 = v_20024 + v_20025;
        let v_20027 = &v_20003[v_20026];
        *v_20027 = v_189;
        workgroupBarrier();
        storageBarrier();
        v_20028 = i32(local_id.x);
        v_20029 = i32(0);
        v_20030 = i32(local_id.y);
        v_20031 = i32(0);
        v_20032 = i32(local_id.z);
        v_20033 = i32(0);
        v_20034 = v_20028 != v_20029;
        v_20035 = v_20030 != v_20031;
        v_20036 = v_20034 | v_20035;
        v_20037 = v_20032 != v_20033;
        v_20038 = v_20036 | v_20037;
        if (v_20038) {
        } else {
            v_20039 = i32(1);
            v_20040 = i32(workgroup_size.x);
            v_20041 = i32(workgroup_size.y);
            v_20042 = i32(workgroup_size.z);
            v_20043 = i64_from_i32(v_20040);
            v_20044 = i64_from_i32(v_20041);
            v_20045 = i64_mul(v_20043, v_20044);
            v_20046 = i64_from_i32(v_20042);
            v_20047 = i64_mul(v_20045, v_20046);
            v_20048 = _c_i64_0;
            v_20049 = i64_ge(v_20047, v_20048);
            v_20050 = _c_i64_1;
            v_20051 = i64_le(v_20047, v_20050);
            v_20052 = v_20049 & v_20051;
            v_20053 = v_20040 * v_20041;
            v_20054 = v_20053 * v_20042;
            v_20000 = v_20039;
            loop {
                v_20055 = v_20000 < v_20054;
                if (!v_20055) { break; }
                let v_20056 = &v_20003[v_20000];
                v_20057 = i32(1);
                v_20058 = v_20000 - v_20057;
                let v_20059 = &v_20003[v_20058];
                v_20060 = *v_20059;
                let v_20061 = &v_20003[v_20000];
                v_20062 = *v_20061;
                v_20063 = v_20060 + v_20062;
                *v_20056 = v_20063;
                v_20064 = i32(1);
                v_20065 = v_20000 + v_20064;
                v_20000 = v_20065;
                // loop continue (back-edge)
            }
        }
        workgroupBarrier();
        storageBarrier();
        v_20066 = i32(workgroup_size.x);
        v_20067 = i32(workgroup_size.y);
        v_20068 = i32(workgroup_size.z);
        v_20069 = i64_from_i32(v_20066);
        v_20070 = i64_from_i32(v_20067);
        v_20071 = i64_mul(v_20069, v_20070);
        v_20072 = i64_from_i32(v_20068);
        v_20073 = i64_mul(v_20071, v_20072);
        v_20074 = _c_i64_0;
        v_20075 = i64_ge(v_20073, v_20074);
        v_20076 = _c_i64_1;
        v_20077 = i64_le(v_20073, v_20076);
        v_20078 = v_20075 & v_20077;
        v_20079 = i32(local_id.x);
        v_20080 = i32(0);
        v_20081 = v_20079 == v_20080;
        v_20082 = i32(local_id.y);
        v_20083 = i32(0);
        v_20084 = v_20082 == v_20083;
        v_20085 = v_20081 & v_20084;
        v_20086 = i32(local_id.z);
        v_20087 = i32(0);
        v_20088 = v_20086 == v_20087;
        v_20089 = v_20085 & v_20088;
        if (v_20089) {
            v_20090 = i32(0);
            v_20001 = v_20090;
        } else {
            v_20091 = i32(local_id.x);
            v_20092 = i32(local_id.y);
            v_20093 = i32(local_id.z);
            v_20094 = i32(workgroup_size.x);
            v_20095 = i32(workgroup_size.y);
            v_20096 = i64_from_i32(v_20094);
            v_20097 = i64_from_i32(v_20095);
            v_20098 = i64_mul(v_20096, v_20097);
            v_20099 = _c_i64_0;
            v_20100 = i64_ge(v_20098, v_20099);
            v_20101 = _c_i64_1;
            v_20102 = i64_le(v_20098, v_20101);
            v_20103 = v_20100 & v_20102;
            v_20104 = v_20094 * v_20095;
            v_20105 = i32(1);
            v_20106 = v_20094 >= v_20105;
            v_20107 = i32(1);
            v_20108 = v_20104 >= v_20107;
            v_20109 = v_20104 >= v_20094;
            v_20110 = v_20092 * v_20094;
            v_20111 = v_20091 + v_20110;
            v_20112 = v_20093 * v_20104;
            v_20113 = v_20111 + v_20112;
            v_20114 = i32(1);
            v_20115 = v_20113 - v_20114;
            let v_20116 = &v_20003[v_20115];
            v_20117 = *v_20116;
            v_20001 = v_20117;
        }
        v_190 = v_20001;
        }
        // --- END inlined helper: ExclusiveScan_115 ---
        *v_187 = v_190;
        let v_191 = &v_92[v_29];
        let v_192 = &v_92[v_29];
        v_193 = *v_192;
        // --- BEGIN inlined helper: ExclusiveScan_115 ---
        {
        v_30002 = i32(2048);
(null)
        v_30004 = i32(local_id.x);
        v_30005 = i32(local_id.y);
        v_30006 = i32(local_id.z);
        v_30007 = i32(workgroup_size.x);
        v_30008 = i32(workgroup_size.y);
        v_30009 = i64_from_i32(v_30007);
        v_30010 = i64_from_i32(v_30008);
        v_30011 = i64_mul(v_30009, v_30010);
        v_30012 = _c_i64_0;
        v_30013 = i64_ge(v_30011, v_30012);
        v_30014 = _c_i64_1;
        v_30015 = i64_le(v_30011, v_30014);
        v_30016 = v_30013 & v_30015;
        v_30017 = v_30007 * v_30008;
        v_30018 = i32(1);
        v_30019 = v_30007 >= v_30018;
        v_30020 = i32(1);
        v_30021 = v_30017 >= v_30020;
        v_30022 = v_30017 >= v_30007;
        v_30023 = v_30005 * v_30007;
        v_30024 = v_30004 + v_30023;
        v_30025 = v_30006 * v_30017;
        v_30026 = v_30024 + v_30025;
        let v_30027 = &v_30003[v_30026];
        *v_30027 = v_193;
        workgroupBarrier();
        storageBarrier();
        v_30028 = i32(local_id.x);
        v_30029 = i32(0);
        v_30030 = i32(local_id.y);
        v_30031 = i32(0);
        v_30032 = i32(local_id.z);
        v_30033 = i32(0);
        v_30034 = v_30028 != v_30029;
        v_30035 = v_30030 != v_30031;
        v_30036 = v_30034 | v_30035;
        v_30037 = v_30032 != v_30033;
        v_30038 = v_30036 | v_30037;
        if (v_30038) {
        } else {
            v_30039 = i32(1);
            v_30040 = i32(workgroup_size.x);
            v_30041 = i32(workgroup_size.y);
            v_30042 = i32(workgroup_size.z);
            v_30043 = i64_from_i32(v_30040);
            v_30044 = i64_from_i32(v_30041);
            v_30045 = i64_mul(v_30043, v_30044);
            v_30046 = i64_from_i32(v_30042);
            v_30047 = i64_mul(v_30045, v_30046);
            v_30048 = _c_i64_0;
            v_30049 = i64_ge(v_30047, v_30048);
            v_30050 = _c_i64_1;
            v_30051 = i64_le(v_30047, v_30050);
            v_30052 = v_30049 & v_30051;
            v_30053 = v_30040 * v_30041;
            v_30054 = v_30053 * v_30042;
            v_30000 = v_30039;
            loop {
                v_30055 = v_30000 < v_30054;
                if (!v_30055) { break; }
                let v_30056 = &v_30003[v_30000];
                v_30057 = i32(1);
                v_30058 = v_30000 - v_30057;
                let v_30059 = &v_30003[v_30058];
                v_30060 = *v_30059;
                let v_30061 = &v_30003[v_30000];
                v_30062 = *v_30061;
                v_30063 = v_30060 + v_30062;
                *v_30056 = v_30063;
                v_30064 = i32(1);
                v_30065 = v_30000 + v_30064;
                v_30000 = v_30065;
                // loop continue (back-edge)
            }
        }
        workgroupBarrier();
        storageBarrier();
        v_30066 = i32(workgroup_size.x);
        v_30067 = i32(workgroup_size.y);
        v_30068 = i32(workgroup_size.z);
        v_30069 = i64_from_i32(v_30066);
        v_30070 = i64_from_i32(v_30067);
        v_30071 = i64_mul(v_30069, v_30070);
        v_30072 = i64_from_i32(v_30068);
        v_30073 = i64_mul(v_30071, v_30072);
        v_30074 = _c_i64_0;
        v_30075 = i64_ge(v_30073, v_30074);
        v_30076 = _c_i64_1;
        v_30077 = i64_le(v_30073, v_30076);
        v_30078 = v_30075 & v_30077;
        v_30079 = i32(local_id.x);
        v_30080 = i32(0);
        v_30081 = v_30079 == v_30080;
        v_30082 = i32(local_id.y);
        v_30083 = i32(0);
        v_30084 = v_30082 == v_30083;
        v_30085 = v_30081 & v_30084;
        v_30086 = i32(local_id.z);
        v_30087 = i32(0);
        v_30088 = v_30086 == v_30087;
        v_30089 = v_30085 & v_30088;
        if (v_30089) {
            v_30090 = i32(0);
            v_30001 = v_30090;
        } else {
            v_30091 = i32(local_id.x);
            v_30092 = i32(local_id.y);
            v_30093 = i32(local_id.z);
            v_30094 = i32(workgroup_size.x);
            v_30095 = i32(workgroup_size.y);
            v_30096 = i64_from_i32(v_30094);
            v_30097 = i64_from_i32(v_30095);
            v_30098 = i64_mul(v_30096, v_30097);
            v_30099 = _c_i64_0;
            v_30100 = i64_ge(v_30098, v_30099);
            v_30101 = _c_i64_1;
            v_30102 = i64_le(v_30098, v_30101);
            v_30103 = v_30100 & v_30102;
            v_30104 = v_30094 * v_30095;
            v_30105 = i32(1);
            v_30106 = v_30094 >= v_30105;
            v_30107 = i32(1);
            v_30108 = v_30104 >= v_30107;
            v_30109 = v_30104 >= v_30094;
            v_30110 = v_30092 * v_30094;
            v_30111 = v_30091 + v_30110;
            v_30112 = v_30093 * v_30104;
            v_30113 = v_30111 + v_30112;
            v_30114 = i32(1);
            v_30115 = v_30113 - v_30114;
            let v_30116 = &v_30003[v_30115];
            v_30117 = *v_30116;
            v_30001 = v_30117;
        }
        v_194 = v_30001;
        }
        // --- END inlined helper: ExclusiveScan_115 ---
        *v_191 = v_194;
        let v_195 = &v_92[v_30];
        let v_196 = &v_92[v_30];
        v_197 = *v_196;
        // --- BEGIN inlined helper: ExclusiveScan_115 ---
        {
        v_40002 = i32(2048);
(null)
        v_40004 = i32(local_id.x);
        v_40005 = i32(local_id.y);
        v_40006 = i32(local_id.z);
        v_40007 = i32(workgroup_size.x);
        v_40008 = i32(workgroup_size.y);
        v_40009 = i64_from_i32(v_40007);
        v_40010 = i64_from_i32(v_40008);
        v_40011 = i64_mul(v_40009, v_40010);
        v_40012 = _c_i64_0;
        v_40013 = i64_ge(v_40011, v_40012);
        v_40014 = _c_i64_1;
        v_40015 = i64_le(v_40011, v_40014);
        v_40016 = v_40013 & v_40015;
        v_40017 = v_40007 * v_40008;
        v_40018 = i32(1);
        v_40019 = v_40007 >= v_40018;
        v_40020 = i32(1);
        v_40021 = v_40017 >= v_40020;
        v_40022 = v_40017 >= v_40007;
        v_40023 = v_40005 * v_40007;
        v_40024 = v_40004 + v_40023;
        v_40025 = v_40006 * v_40017;
        v_40026 = v_40024 + v_40025;
        let v_40027 = &v_40003[v_40026];
        *v_40027 = v_197;
        workgroupBarrier();
        storageBarrier();
        v_40028 = i32(local_id.x);
        v_40029 = i32(0);
        v_40030 = i32(local_id.y);
        v_40031 = i32(0);
        v_40032 = i32(local_id.z);
        v_40033 = i32(0);
        v_40034 = v_40028 != v_40029;
        v_40035 = v_40030 != v_40031;
        v_40036 = v_40034 | v_40035;
        v_40037 = v_40032 != v_40033;
        v_40038 = v_40036 | v_40037;
        if (v_40038) {
        } else {
            v_40039 = i32(1);
            v_40040 = i32(workgroup_size.x);
            v_40041 = i32(workgroup_size.y);
            v_40042 = i32(workgroup_size.z);
            v_40043 = i64_from_i32(v_40040);
            v_40044 = i64_from_i32(v_40041);
            v_40045 = i64_mul(v_40043, v_40044);
            v_40046 = i64_from_i32(v_40042);
            v_40047 = i64_mul(v_40045, v_40046);
            v_40048 = _c_i64_0;
            v_40049 = i64_ge(v_40047, v_40048);
            v_40050 = _c_i64_1;
            v_40051 = i64_le(v_40047, v_40050);
            v_40052 = v_40049 & v_40051;
            v_40053 = v_40040 * v_40041;
            v_40054 = v_40053 * v_40042;
            v_40000 = v_40039;
            loop {
                v_40055 = v_40000 < v_40054;
                if (!v_40055) { break; }
                let v_40056 = &v_40003[v_40000];
                v_40057 = i32(1);
                v_40058 = v_40000 - v_40057;
                let v_40059 = &v_40003[v_40058];
                v_40060 = *v_40059;
                let v_40061 = &v_40003[v_40000];
                v_40062 = *v_40061;
                v_40063 = v_40060 + v_40062;
                *v_40056 = v_40063;
                v_40064 = i32(1);
                v_40065 = v_40000 + v_40064;
                v_40000 = v_40065;
                // loop continue (back-edge)
            }
        }
        workgroupBarrier();
        storageBarrier();
        v_40066 = i32(workgroup_size.x);
        v_40067 = i32(workgroup_size.y);
        v_40068 = i32(workgroup_size.z);
        v_40069 = i64_from_i32(v_40066);
        v_40070 = i64_from_i32(v_40067);
        v_40071 = i64_mul(v_40069, v_40070);
        v_40072 = i64_from_i32(v_40068);
        v_40073 = i64_mul(v_40071, v_40072);
        v_40074 = _c_i64_0;
        v_40075 = i64_ge(v_40073, v_40074);
        v_40076 = _c_i64_1;
        v_40077 = i64_le(v_40073, v_40076);
        v_40078 = v_40075 & v_40077;
        v_40079 = i32(local_id.x);
        v_40080 = i32(0);
        v_40081 = v_40079 == v_40080;
        v_40082 = i32(local_id.y);
        v_40083 = i32(0);
        v_40084 = v_40082 == v_40083;
        v_40085 = v_40081 & v_40084;
        v_40086 = i32(local_id.z);
        v_40087 = i32(0);
        v_40088 = v_40086 == v_40087;
        v_40089 = v_40085 & v_40088;
        if (v_40089) {
            v_40090 = i32(0);
            v_40001 = v_40090;
        } else {
            v_40091 = i32(local_id.x);
            v_40092 = i32(local_id.y);
            v_40093 = i32(local_id.z);
            v_40094 = i32(workgroup_size.x);
            v_40095 = i32(workgroup_size.y);
            v_40096 = i64_from_i32(v_40094);
            v_40097 = i64_from_i32(v_40095);
            v_40098 = i64_mul(v_40096, v_40097);
            v_40099 = _c_i64_0;
            v_40100 = i64_ge(v_40098, v_40099);
            v_40101 = _c_i64_1;
            v_40102 = i64_le(v_40098, v_40101);
            v_40103 = v_40100 & v_40102;
            v_40104 = v_40094 * v_40095;
            v_40105 = i32(1);
            v_40106 = v_40094 >= v_40105;
            v_40107 = i32(1);
            v_40108 = v_40104 >= v_40107;
            v_40109 = v_40104 >= v_40094;
            v_40110 = v_40092 * v_40094;
            v_40111 = v_40091 + v_40110;
            v_40112 = v_40093 * v_40104;
            v_40113 = v_40111 + v_40112;
            v_40114 = i32(1);
            v_40115 = v_40113 - v_40114;
            let v_40116 = &v_40003[v_40115];
            v_40117 = *v_40116;
            v_40001 = v_40117;
        }
        v_198 = v_40001;
        }
        // --- END inlined helper: ExclusiveScan_115 ---
        *v_195 = v_198;
        workgroupBarrier();
        storageBarrier();
        if (!v_132) {
            v_199 = i32(0);
            v_200 = i32(local_id.x);
            let v_201 = &v_92[v_200];
            v_202 = *v_201;
            v_203 = v_49 == v_199;
            v_52 = v_40 & v_203;
            v_204 = i32(1);
            v_205 = i32(0);
            v_206 = select(v_205, v_204, v_52);
            v_53 = v_202 + v_206;
            *v_201 = v_53;
            let v_207 = &param1[(i32(_scalar_params[5]) + v_37)];
            v_208 = *v_201;
            *v_207 = v_208;
            v_209 = i32(1);
            let v_210 = &v_92[v_31];
            v_211 = *v_210;
            v_212 = v_49 == v_209;
            v_54 = v_40 & v_212;
            v_213 = i32(1);
            v_214 = i32(0);
            v_215 = select(v_214, v_213, v_54);
            v_55 = v_211 + v_215;
            *v_210 = v_55;
            v_56 = v_86 + v_37;
            let v_216 = &param1[(i32(_scalar_params[5]) + v_56)];
            v_217 = *v_210;
            *v_216 = v_217;
            v_218 = i32(2);
            let v_219 = &v_92[v_32];
            v_220 = *v_219;
            v_221 = v_49 == v_218;
            v_57 = v_40 & v_221;
            v_222 = i32(1);
            v_223 = i32(0);
            v_224 = select(v_223, v_222, v_57);
            v_58 = v_220 + v_224;
            *v_219 = v_58;
            v_59 = v_33 + v_37;
            let v_225 = &param1[(i32(_scalar_params[5]) + v_59)];
            v_226 = *v_219;
            *v_225 = v_226;
            let v_227 = &v_92[v_35];
            v_228 = *v_227;
            v_229 = v_49 == v_34;
            v_60 = v_40 & v_229;
            v_230 = i32(1);
            v_231 = i32(0);
            v_232 = select(v_231, v_230, v_60);
            v_61 = v_228 + v_232;
            *v_227 = v_61;
            v_62 = v_36 + v_37;
            let v_233 = &param1[(i32(_scalar_params[5]) + v_62)];
            v_234 = *v_227;
            *v_233 = v_234;
        } else {
        }
        workgroupBarrier();
        storageBarrier();
        v_235 = i32(workgroup_size.x);
        v_63 = v_37 * v_235;
        v_236 = i32(local_id.x);
        v_237 = i32(8);
        v_64 = v_49 << u32(v_237);
        v_65 = v_236 + v_64;
        let v_238 = &v_92[v_65];
        v_239 = *v_238;
        v_66 = v_63 + v_239;
        v_67 = v_40 & v_20;
        v_240 = i32(1);
        v_241 = i32(0);
        v_242 = select(v_241, v_240, v_67);
        v_68 = v_66 - v_242;
        v_69 = i32(1);
        v_70 = v_69;
        v_71 = v_68;
        loop {
            v_243 = v_70 <= v_49;
            if (!v_243) {
                break;
            }
            v_244 = i32(8);
            v_77 = v_70 << u32(v_244);
            v_245 = i32(1);
            v_78 = v_77 - v_245;
            let v_246 = &v_92[v_78];
            v_247 = *v_246;
            v_248 = i32(1);
            v_79 = v_70 - v_248;
            v_249 = v_79 == v_49;
            v_250 = i32(1);
            v_251 = i32(0);
            v_252 = select(v_251, v_250, v_249);
            v_80 = v_247 + v_252;
            v_81 = v_71 + v_80;
            v_253 = i32(1);
            v_82 = v_70 + v_253;
            v_70 = v_82;
            v_71 = v_81;
        }
        v_254 = i64_ge(v_39, v_0);
        if (!v_254) {
            v_255 = i32(0);
            v_256 = v_71 >= v_255;
            v_257 = v_71 < v_22;
            v_72 = v_256 & v_257;
            v_258 = i32(0);
            v_259 = v_71 == v_258;
            v_73 = v_259 & v_23;
            v_74 = v_72 | v_73;
            let v_260 = &param0_f0[(i32(_scalar_params[4]) + v_71)];
            *v_260 = v_46;
        } else {
        }
        workgroupBarrier();
        storageBarrier();
        v_261 = i32(num_workgroups.x * num_workgroups.y);
        v_75 = v_37 + v_261;
        v_76 = v_38 + v_24;
        v_37 = v_75;
        v_38 = v_76;
    }
    return;
}
(null)
=== END WGSL DUMP ===
