=== WGSL DUMP: RadixSortKernel2 (555 lines) ===
// Kernel: RadixSortKernel2
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//
(null)
// Kernel: RadixSortKernel2_106
// WorkgroupSize: 256
// Emulation: i64
(null)
(null)
// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}
(null)
// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}
(null)
// emu_i64/emu_u64 addition with carry
fn i64_add(a: emu_i64, b: emu_i64) -> emu_i64 {
    let lo = a.x + b.x;
    let carry = select(0u, 1u, lo < a.x);
    let hi = a.y + b.y + carry;
    return emu_i64(lo, hi);
}
(null)
// emu_i64 negation (two's complement)
fn i64_neg(a: emu_i64) -> emu_i64 {
    let inv = emu_i64(~a.x, ~a.y);
    return i64_add(inv, emu_i64(1u, 0u));
}
(null)
// emu_u64 multiplication (full 64x64 -> 64-bit result, ignoring overflow)
fn u64_mul(a: emu_u64, b: emu_u64) -> emu_u64 {
    // Split into 16-bit parts for WGSL compatibility
    let a_lo = a.x & 0xFFFFu;
    let a_hi = a.x >> 16u;
    let b_lo = b.x & 0xFFFFu;
    let b_hi = b.x >> 16u;
    
    // Partial products
    let p0 = a_lo * b_lo;
    let p1 = a_lo * b_hi;
    let p2 = a_hi * b_lo;
    let p3 = a_hi * b_hi;
    
    // Combine low parts
    let mid = (p0 >> 16u) + (p1 & 0xFFFFu) + (p2 & 0xFFFFu);
    let lo = (p0 & 0xFFFFu) | ((mid & 0xFFFFu) << 16u);
    
    // Combine high parts
    let hi = p3 + (p1 >> 16u) + (p2 >> 16u) + (mid >> 16u) + a.x * b.y + a.y * b.x;
    
    return emu_u64(lo, hi);
}
(null)
// emu_i64 multiplication (uses u64_mul internally)
fn i64_mul(a: emu_i64, b: emu_i64) -> emu_i64 {
    let neg_a = (a.y & 0x80000000u) != 0u;
    let neg_b = (b.y & 0x80000000u) != 0u;
    var abs_a = a;
    var abs_b = b;
    if (neg_a) { abs_a = i64_neg(a); }
    if (neg_b) { abs_b = i64_neg(b); }
    var result = u64_mul(abs_a, abs_b);
    if (neg_a != neg_b) { result = i64_neg(result); }
    return result;
}
(null)
// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}
(null)
// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}
(null)
// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}
(null)
// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}
(null)
(null)
// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);
(null)
struct struct_40 {
    field_0 : i32,
    field_1 : emu_i64,
    field_2 : i32,
};
(null)
// Param 0: Struct<View<Int32, Generic> [0], Int64 [8], Int8 [16]> (Element: Int32)
// Body struct field 0: View<Int32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param0_f0 : array<i32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 1: Struct<View<Int32, Generic> [0], Int64 [8], Int8 [16]> (Element: Int32)
// Body struct field 0: View<Int32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param1_f0 : array<i32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: View<Int32, Generic> (Element: Int32)
@group(0) @binding(2) var<storage, read_write> param2 : array<i32>;
// Param 3: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// Param 4: Int32 (Element: Int32)
// -> Packed scalar at slot 1 (1 slots, type: i32)
// Param 5: Int32 (Element: Int32)
// -> Packed scalar at slot 2 (1 slots, type: i32)
// View offset for param1000 at scalar slot 3
// View offset for param2000 at scalar slot 4
// View offset for param2 at scalar slot 5
@group(0) @binding(3) var<storage, read> _scalar_params : array<u32>;
(null)
const workgroup_size : vec3<u32> = vec3<u32>(256u, 1u, 1u);
(null)
@compute @workgroup_size(256)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;
(null)
    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : i32 = 0;
    var v_2 : emu_i64 = emu_i64(0u, 0u);
    var v_3 : emu_i64 = emu_i64(0u, 0u);
    var v_4 : bool = false;
    var v_5 : emu_i64 = emu_i64(0u, 0u);
    var v_6 : emu_i64 = emu_i64(0u, 0u);
    var v_7 : bool = false;
    var v_8 : emu_i64 = emu_i64(0u, 0u);
    var v_9 : emu_i64 = emu_i64(0u, 0u);
    var v_10 : bool = false;
    var v_11 : i32 = 0;
    var v_12 : i32 = 0;
    var v_13 : bool = false;
    var v_14 : i32 = 0;
    var v_15 : bool = false;
    var v_16 : i32 = 0;
    var v_17 : i32 = 0;
    var v_18 : bool = false;
    var v_19 : i32 = 0;
    var v_20 : bool = false;
    var v_21 : i32 = 0;
    var v_22 : i32 = 0;
    var v_23 : i32 = 0;
    var v_24 : emu_i64 = emu_i64(0u, 0u);
    var v_25 : i32 = 0;
    var v_26 : bool = false;
    var v_27 : bool = false;
    var v_28 : bool = false;
    var v_29 : i32 = 0;
    var v_30 : i32 = 0;
    var v_31 : i32 = 0;
    var v_32 : i32 = 0;
    var v_33 : i32 = 0;
    var v_34 : i32 = 0;
    var v_35 : i32 = 0;
    var v_36 : i32 = 0;
    var v_37 : i32 = 0;
    var v_38 : i32 = 0;
    var v_39 : i32 = 0;
    var v_40 : i32 = 0;
    var v_41 : i32 = 0;
    var v_42 : i32 = 0;
    var v_43 : i32 = 0;
    var v_44 : i32 = 0;
    var v_45 : i32 = 0;
    var v_46 : i32 = 0;
    var v_47 : i32 = 0;
    var v_48 : bool = false;
    var v_49 : bool = false;
    var v_50 : bool = false;
    var v_51 : i32 = 0;
    var v_52 : i32 = 0;
    var v_53 : i32 = 0;
    var v_54 : i32 = 0;
    var v_55 : i32 = 0;
    var v_56 : i32 = 0;
    var v_57 : i32 = 0;
    var v_58 : i32 = 0;
    var v_59 : i32 = 0;
    var v_60 : i32 = 0;
    var v_61 : i32 = 0;
    var v_62 : i32 = 0;
    var v_63 : i32 = 0;
    var v_64 : i32 = 0;
    let v_65_f0 = &param0_f0;
    var v_65_f1 = i64_from_i32(i32(arrayLength(&param0_f0)));
    let v_66_f0 = &param1_f0;
    var v_66_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_67 = &param2;
    var v_68 = bitcast<i32>(_scalar_params[0]);
    var v_69 = bitcast<i32>(_scalar_params[1]);
    var v_70 = bitcast<i32>(_scalar_params[2]);
    var v_74 : i32;
    var v_75 : i32;
    var v_76 : i32;
    var v_77 : i32;
    var v_78 : i32;
    var v_79 : i32;
    var v_80 : i32;
    var v_81 : i32;
    var v_82 : i32;
    var v_86 : emu_i64;
    var v_88 : emu_i64;
    var v_93 : emu_i64;
    var v_95 : emu_i64;
    var v_100 : emu_i64;
    var v_102 : emu_i64;
    var v_104 : emu_i64;
    var v_106 : emu_i64;
    var v_108 : i32;
    var v_109 : i32;
    var v_110 : i32;
    var v_111 : i32;
    var v_112 : emu_i64;
    var v_114 : emu_i64;
    var v_116 : i32;
    var v_117 : i32;
    var v_118 : i32;
    var v_122 : i32;
    var v_125 : i32;
    var v_128 : i32;
    var v_129 : i32;
    var v_130 : i32;
    var v_132 : i32;
    var v_135 : i32;
    var v_138 : i32;
    var v_139 : i32;
    var v_141 : i32;
    var v_144 : i32;
    var v_146 : i32;
    var v_149 : i32;
    var v_152 : i32;
    var v_73 : emu_i64;
    var v_83 : emu_i64;
    var v_84 : emu_i64;
    var v_85 : emu_i64;
    var v_87 : bool;
    var v_89 : bool;
    var v_90 : emu_i64;
    var v_91 : emu_i64;
    var v_92 : emu_i64;
    var v_94 : bool;
    var v_96 : bool;
    var v_97 : emu_i64;
    var v_98 : emu_i64;
    var v_99 : emu_i64;
    var v_101 : bool;
    var v_103 : bool;
    var v_105 : bool;
    var v_107 : bool;
    var v_113 : bool;
    var v_115 : bool;
    var v_119 : bool;
    var v_120 : bool;
    var v_121 : bool;
    var v_123 : bool;
    var v_124 : bool;
    var v_126 : bool;
    var v_131 : bool;
    var v_133 : bool;
    var v_136 : bool;
    var v_140 : bool;
    var v_142 : bool;
    var v_145 : bool;
    var v_147 : bool;
    var v_148 : bool;
    var v_150 : bool;
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
(null)
    let v_71 = v_65_f0;
    let v_72 = v_66_f0;
    // BB_12191 (UBranch(B12198))
(null)
    v_0 = v_65_f1;
(null)
    v_73 = v_66_f1;
    v_1 = i32(group_id.x + group_id.y * num_workgroups.x);
    v_74 = i32(group_id.x + group_id.y * num_workgroups.x);
    v_75 = i32(group_id.y);
    v_76 = i32(group_id.z);
    v_77 = i32(local_id.x);
    v_78 = i32(local_id.y);
    v_79 = i32(local_id.z);
    v_80 = i32(workgroup_size.x);
    v_81 = i32(workgroup_size.y);
    v_82 = i32(workgroup_size.z);
    v_83 = i64_from_i32(v_77);
    v_84 = i64_from_i32(v_74);
    v_85 = i64_from_i32(v_80);
    v_2 = i64_mul(v_84, v_85);
    v_3 = i64_add(v_83, v_2);
    v_86 = _c_i64_0;
    v_87 = i64_ge(v_3, v_86);
    v_88 = _c_i64_1;
    v_89 = i64_le(v_3, v_88);
    v_4 = v_87 & v_89;
    v_90 = i64_from_i32(v_78);
    v_91 = i64_from_i32(v_75);
    v_92 = i64_from_i32(v_81);
    v_5 = i64_mul(v_91, v_92);
    v_6 = i64_add(v_90, v_5);
    v_93 = _c_i64_0;
    v_94 = i64_ge(v_6, v_93);
    v_95 = _c_i64_1;
    v_96 = i64_le(v_6, v_95);
    v_7 = v_94 & v_96;
    v_97 = i64_from_i32(v_79);
    v_98 = i64_from_i32(v_76);
    v_99 = i64_from_i32(v_82);
    v_8 = i64_mul(v_98, v_99);
    v_9 = i64_add(v_97, v_8);
    v_100 = _c_i64_0;
    v_101 = i64_ge(v_9, v_100);
    v_102 = _c_i64_1;
    v_103 = i64_le(v_9, v_102);
    v_10 = v_101 & v_103;
    v_11 = v_74 * v_80;
    v_12 = v_77 + v_11;
    v_104 = _c_i64_0;
    v_105 = i64_ge(v_0, v_104);
    v_106 = _c_i64_1;
    v_107 = i64_le(v_0, v_106);
    v_13 = v_105 & v_107;
    v_14 = i64_to_i32(v_0);
    v_108 = i32(0);
    v_15 = v_14 == v_108;
    v_109 = i32(4);
    v_110 = i32(1);
    v_16 = i32(3);
    v_111 = i32(31);
    v_17 = v_70 & v_111;
    v_112 = _c_i64_0;
    v_113 = i64_ge(v_73, v_112);
    v_114 = _c_i64_1;
    v_115 = i64_le(v_73, v_114);
    v_18 = v_113 & v_115;
    v_19 = i64_to_i32(v_73);
    v_116 = i32(0);
    v_20 = v_19 == v_116;
    v_117 = i32(num_workgroups.x * num_workgroups.y);
    v_118 = i32(workgroup_size.x);
    v_21 = v_117 * v_118;
    v_22 = v_12;
    v_23 = v_1;
    // LOOP header=BB_12198 exits=[B12199]
    loop {
        v_119 = v_22 < v_69;
        let _uf_break_v_119 = (v_23 * i32(workgroup_size.x)) < v_69;
        if (!_uf_break_v_119) {
            break;
        }
        // BB_12200 (IfBranch(T=B12202,F=B12201) inLoop stop=B12198)
        v_24 = i64_from_i32(v_22);
        v_120 = i64_lt(v_24, v_0);
        v_25 = i32(0);
        v_121 = i64_ge(v_24, v_0);
        // IF from BB_12200: merge=BB_12202 true=BB_12202 false=BB_12201
        if (!v_121) {
            // BB_12201 (UBranch(B12202) inLoop stop=B12202)
            v_122 = i32(0);
            v_123 = v_22 >= v_122;
            v_124 = v_22 < v_14;
            v_26 = v_123 & v_124;
            v_125 = i32(0);
            v_126 = v_22 == v_125;
            v_27 = v_126 & v_15;
            v_28 = v_26 | v_27;
            let v_127 = &param0_f0[(i32(_scalar_params[3]) + v_22)];
            v_29 = *v_127;
            v_30 = v_29;
        } else {
            v_30 = v_25;
        }
        // MERGE → BB_12202
        // BB_12202 (IfBranch(T=B12204,F=B12203) inLoop stop=B12198)
        v_128 = i32(-2147483648);
        v_31 = v_30 ^ v_128;
        v_32 = v_31 >> u32(v_17);
        v_33 = v_32 & v_16;
        v_34 = i32(0);
        v_35 = v_33 * v_68;
        v_36 = v_35 + v_23;
        v_129 = i32(1);
        v_37 = v_36 - v_129;
        v_130 = i32(0);
        v_131 = v_37 >= v_130;
        // IF from BB_12202: merge=BB_12204 true=BB_12204 false=BB_12203
        if (!v_131) {
            // BB_12203 (UBranch(B12204) inLoop stop=B12204)
            v_38 = i32(0);
            v_39 = v_38;
        } else {
            v_39 = v_37;
        }
        // MERGE → BB_12204
        // BB_12204 (IfBranch(T=B12206,F=B12205) inLoop stop=B12198)
        v_132 = i32(1);
        v_133 = v_36 < v_132;
        // IF from BB_12204: merge=BB_12207 true=BB_12206 false=BB_12205
        if (v_133) {
            // BB_12206 (UBranch(B12207) inLoop stop=B12207)
            v_41 = i32(0);
            v_42 = v_41;
        } else {
            // BB_12205 (UBranch(B12207) inLoop stop=B12207)
            let v_134 = &param2[(i32(_scalar_params[5]) + v_39)];
            v_40 = *v_134;
            v_42 = v_40;
        }
        // MERGE → BB_12207
        // BB_12207 (UBranch(B12208) inLoop stop=B12198)
        v_135 = i32(local_id.x);
        v_43 = v_42 + v_135;
        v_44 = i32(0);
        v_45 = v_44;
        v_46 = v_34;
        // LOOP header=BB_12208 exits=[B12209]
        loop {
            v_136 = v_45 < v_33;
            if (!v_136) {
                break;
            }
            // BB_12212 (IfBranch(T=B12214,F=B12213) inLoop stop=B12208)
            v_53 = v_45 * v_68;
            v_54 = v_53 + v_23;
            let v_137 = &param2[(i32(_scalar_params[5]) + v_54)];
            v_55 = *v_137;
            v_138 = i32(1);
            v_56 = v_54 - v_138;
            v_139 = i32(0);
            v_140 = v_56 >= v_139;
            // IF from BB_12212: merge=BB_12214 true=BB_12214 false=BB_12213
            if (!v_140) {
                // BB_12213 (UBranch(B12214) inLoop stop=B12214)
                v_57 = i32(0);
                v_58 = v_57;
            } else {
                v_58 = v_56;
            }
            // MERGE → BB_12214
            // BB_12214 (IfBranch(T=B12216,F=B12215) inLoop stop=B12208)
            v_141 = i32(1);
            v_142 = v_54 < v_141;
            // IF from BB_12214: merge=BB_12217 true=BB_12216 false=BB_12215
            if (v_142) {
                // BB_12216 (UBranch(B12217) inLoop stop=B12217)
                v_60 = i32(0);
                v_61 = v_60;
            } else {
                // BB_12215 (UBranch(B12217) inLoop stop=B12217)
                let v_143 = &param2[(i32(_scalar_params[5]) + v_58)];
                v_59 = *v_143;
                v_61 = v_59;
            }
            // MERGE → BB_12217
            // BB_12217 (UBranch(B12208) inLoop stop=B12208)
            v_62 = v_55 - v_61;
            v_63 = v_46 + v_62;
            v_144 = i32(1);
            v_64 = v_45 + v_144;
            v_45 = v_64;
            v_46 = v_63;
        }
        // BB_12209 (IfBranch(T=B12211,F=B12210) inLoop stop=B12198)
        v_47 = v_43 - v_46;
        v_145 = i64_ge(v_24, v_0);
        // IF from BB_12209: merge=BB_12211 true=BB_12211 false=BB_12210
        if (!v_145) {
            // BB_12210 (UBranch(B12211) inLoop stop=B12211)
            v_146 = i32(0);
            v_147 = v_47 >= v_146;
            v_148 = v_47 < v_19;
            v_48 = v_147 & v_148;
            v_149 = i32(0);
            v_150 = v_47 == v_149;
            v_49 = v_150 & v_20;
            v_50 = v_48 | v_49;
            let v_151 = &param1_f0[(i32(_scalar_params[4]) + v_47)];
            *v_151 = v_30;
        } else {
        }
        // MERGE → BB_12211
        // BB_12211 (UBranch(B12198) inLoop stop=B12198)
        v_152 = i32(num_workgroups.x * num_workgroups.y);
        v_51 = v_23 + v_152;
        v_52 = v_22 + v_21;
        v_22 = v_52;
        v_23 = v_51;
    }
    // BB_12199 (Return)
    return;
}
(null)
=== END WGSL DUMP ===
