// Kernel: Tests23_DecodeUintLongFormKernel
// Workgroup: 64
// SharedMem: 0B
// Bindings: 4
// Time: 2026-05-05T13:17:48.8400000Z

// Kernel: Tests23_DecodeUintLongFormKernel
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: Tests23_DecodeUintLongFormKernel_9
// WorkgroupSize: 64


// ============ F32 Special Value Helpers ============

var<private> _ilgpu_runtime_zero : u32 = 0u;
fn _f32_pos_inf() -> f32 { return bitcast<f32>(0x7F800000u | _ilgpu_runtime_zero); }
fn _f32_neg_inf() -> f32 { return bitcast<f32>(0xFF800000u | _ilgpu_runtime_zero); }
fn _f32_qnan()    -> f32 { return bitcast<f32>(0x7FC00000u | _ilgpu_runtime_zero); }

override _ilgpu_user_dim : u32 = 4294967295u;

// Param 1: View<Int8, Generic> (Element: Int8)
@group(0) @binding(0) var<storage, read_write> param1 : array<atomic<u32>>;
// Param 2: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// Param 3: Int32 (Element: Int32)
// -> Packed scalar at slot 1 (1 slots, type: i32)
// Param 4: View<Int32, Generic> (Element: Int32)
@group(0) @binding(1) var<storage, read_write> param4 : array<i32>;
// Param 5: View<Int32, Generic> (Element: Int32)
@group(0) @binding(2) var<storage, read_write> param5 : array<i32>;
// Param 6: Int32 (Element: Int32)
// -> Packed scalar at slot 2 (1 slots, type: i32)
// View offset for param1 at scalar slot 3
// View offset for param4 at scalar slot 4
// View offset for param5 at scalar slot 5
@group(0) @binding(3) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;
    // Seed the runtime-zero used by F32 special-value helpers from a
    // @builtin value so Naga's const-evaluator cannot fold it. Required
    // because `bitcast<f32>(const_u32_with_inf_bit_pattern)` is rejected
    // at shader creation. See WGSLEmulationLibrary.F32SpecialValueFunctions.
    _ilgpu_runtime_zero = local_id.x ^ local_id.x;

    var v_0 : i32 = 0;
    var v_1 : i32 = 0;
    var v_2 : i32 = 0;
    var v_3 : i32 = 0;
    var v_4 : i32 = 0;
    var v_5 : i32 = 0;
    var v_6 : i32 = 0;
    var v_7 : i32 = 0;
    var v_8 : i32 = 0;
    var v_9 : i32 = 0;
    var v_10 : i32 = 0;
    var v_11 : i32 = 0;
    var v_12 : i32 = 0;
    var v_13 : i32 = 0;
    var v_14 : i32 = 0;
    var v_15 : i32 = 0;
    var v_16 : i32 = 0;
    var v_17 : i32 = 0;
    var v_18 : i32 = 0;
    var v_19 : i32 = 0;
    var v_20 : i32 = 0;
    var v_21 : i32 = 0;
    var v_22 : i32 = 0;
    var v_23 : i32 = 0;
    var v_24 : i32 = 0;
    var v_25 : i32 = 0;
    var v_26 : i32 = 0;
    var v_27 : i32 = 0;
    var v_28 : i32 = 0;
    var v_29 : i32 = 0;
    var v_30 : i32 = 0;
    var v_31 : i32 = 0;
    var v_32 : i32 = 0;
    var v_33 : i32 = 0;
    var v_34 : i32 = 0;
    var v_35 : i32 = 0;
    var v_36 : i32 = 0;
    var v_37 : i32 = 0;
    var v_38 : i32 = 0;
    var v_39 : i32 = 0;
    var v_40 : i32 = 0;
    var v_41 : i32 = 0;
    var v_42 : i32 = 0;
    var v_43 : i32 = 0;
    var v_44 : i32 = 0;
    var v_45 : i32 = 0;
    var v_46 : i32 = 0;
    var v_47 : i32 = 0;
    var v_48 : i32 = 0;
    var v_49 : i32 = 0;
    var v_50 : i32 = 0;
    var v_51 : i32 = 0;
    var v_52 : i32 = 0;
    var v_53 : i32 = 0;
    var v_54 : i32 = 0;
    var v_55 : i32 = 0;
    var v_56 : i32 = 0;
    var v_57 : i32 = 0;
    var v_58 : i32 = 0;
    var v_59 : i32 = 0;
    var v_60 : i32 = 0;
    var v_61 : i32 = 0;
    var v_62 : i32 = 0;
    var v_63 : i32 = 0;
    var v_64 : i32 = 0;
    var v_65 : i32 = 0;
    var v_66 : i32 = 0;
    var v_67 : i32 = 0;
    var v_68 : i32 = 0;
    var v_69 : i32 = 0;
    var v_70 : i32 = 0;
    var v_71 : i32 = 0;
    var v_72 : i32 = 0;
    var v_73 : i32 = 0;
    var v_74 : i32 = 0;
    var v_75 : i32 = 0;
    var v_76 : i32 = 0;
    var v_77 : i32 = 0;
    var v_78 : i32 = 0;
    var v_79 : i32 = 0;
    var v_80 : i32 = 0;
    var v_81 : i32 = 0;
    var v_82 : i32 = 0;
    var v_83 : i32 = 0;
    var v_84 : i32 = 0;
    var v_85 : i32 = 0;
    var v_86 : i32 = 0;
    var v_87 : i32 = 0;
    var v_88 : i32 = 0;
    var v_89 : i32 = 0;
    var v_90 : i32 = 0;
    var v_91 : i32 = 0;
    var v_92 : i32 = 0;
    var v_93 : i32 = 0;
    var v_94 : i32 = 0;
    var v_95 : i32 = 0;
    var v_96 : i32 = 0;
    var v_97 : i32 = 0;
    var v_98 : i32 = 0;
    var v_99 : i32 = 0;
    var v_100 : i32 = 0;
    var v_101 : i32 = 0;
    var v_102 : i32 = 0;
    var v_103 : i32 = 0;
    var v_104 : i32 = 0;
    var v_105 : i32 = 0;
    var v_106 : i32 = 0;
    var v_107 : i32 = 0;
    var v_108 : i32 = 0;
    var v_109 : i32 = 0;
    var v_110 : i32 = 0;
    var v_111 : i32 = 0;
    var v_112 : i32 = 0;
    var v_113 : i32 = 0;
    var v_114 : i32 = 0;
    var v_115 : i32 = 0;
    var v_116 : i32 = 0;
    var v_117 : i32 = 0;
    var v_118 : i32 = 0;
    var v_119 : i32 = 0;
    var v_120 : i32 = 0;
    var v_121 : i32 = 0;
    var v_122 : i32 = 0;
    var v_123 : i32 = 0;
    var v_124 : i32 = 0;
    var v_125 : i32 = 0;
    var v_126 : i32 = 0;
    var v_127 : i32 = 0;
    var v_128 : i32 = 0;
    var v_129 : i32 = 0;
    var v_130 : i32 = 0;
    var v_131 : i32 = 0;
    var v_132 : i32 = 0;
    var v_133 : i32 = 0;
    var v_134 : i32 = 0;
    var v_135 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_135) >= _ilgpu_user_dim) { return; }
    var v_137 = bitcast<i32>(_scalar_params[0]);
    var v_138 = bitcast<i32>(_scalar_params[1]);
    let v_139 = &param4;
    let v_140 = &param5;
    var v_141 = bitcast<i32>(_scalar_params[2]);
    var v_144 : i32;
    var v_145 : i32;
    var v_146 : i32;
    var v_147 : i32;
    var v_148 : i32;
    var v_149 : i32;
    var v_150 : i32;
    var v_154 : i32;
    var v_156 : i32;
    var v_157 : i32;
    var v_159 : i32;
    var v_160 : i32;
    var v_161 : i32;
    var v_163 : i32;
    var v_165 : i32;
    var v_166 : i32;
    var v_167 : i32;
    var v_168 : i32;
    var v_170 : i32;
    var v_171 : i32;
    var v_173 : i32;
    var v_176 : i32;
    var v_177 : i32;
    var v_178 : i32;
    var v_179 : i32;
    var v_180 : i32;
    var v_181 : i32;
    var v_182 : i32;
    var v_183 : i32;
    var v_184 : i32;
    var v_185 : i32;
    var v_186 : i32;
    var v_188 : i32;
    var v_189 : i32;
    var v_190 : i32;
    var v_191 : i32;
    var v_193 : i32;
    var v_194 : i32;
    var v_196 : i32;
    var v_199 : i32;
    var v_200 : i32;
    var v_201 : i32;
    var v_202 : i32;
    var v_203 : i32;
    var v_204 : i32;
    var v_205 : i32;
    var v_206 : i32;
    var v_209 : i32;
    var v_210 : i32;
    var v_211 : i32;
    var v_213 : i32;
    var v_215 : i32;
    var v_216 : i32;
    var v_217 : i32;
    var v_218 : i32;
    var v_219 : i32;
    var v_221 : i32;
    var v_142 : bool;
    var v_151 : bool;
    var v_155 : bool;
    var v_158 : bool;
    var v_162 : bool;
    var v_164 : bool;
    var v_169 : bool;
    var v_172 : bool;
    var v_174 : bool;
    var v_187 : bool;
    var v_192 : bool;
    var v_195 : bool;
    var v_197 : bool;
    var v_207 : bool;
    var v_208 : bool;
    var v_212 : bool;
    var v_220 : bool;
    var v_143 : i32;
    var v_175 : i32;
    var v_198 : i32;
    var v_214 : i32;

















    v_0 = i32(0);
    v_1 = i32(0);
    v_2 = i32(0);
    v_3 = i32(0);
    v_142 = bitcast<u32>(v_138) <= bitcast<u32>(v_0);
    if (v_142) {
        v_6 = i32(0);
        v_7 = v_6;
        v_8 = v_0;
    } else {
        v_143 = (i32(_scalar_params[3]) + v_137);
        v_144 = i32(((u32(atomicLoad(&param1[(u32(v_143) / 4u)])) >> ((u32(v_143) % 4u) * 8u)) & 0xFFu));
        v_4 = i32(v_144);
        v_145 = i32(1);
        v_5 = i32(1);
        v_7 = v_4;
        v_8 = v_5;
    }
    v_146 = i32(2);
    v_147 = i32(1);
    v_148 = i32(1);
    v_149 = i32(1);
    v_9 = v_7 >> u32(v_149);
    v_10 = v_148 - v_9;
    v_150 = i32(8);
    v_11 = i32(512);
    v_12 = i32(0);
    v_13 = v_12;
    v_14 = v_8;
    v_15 = v_1;
    v_16 = v_2;
    v_17 = v_3;
    v_18 = v_11;
    v_19 = v_10;
    v_20 = v_7;
    loop {
        v_151 = v_13 < v_141;
        if (!v_151) {
            break;
        }
        let v_152 = &param5[(i32(_scalar_params[5]) + v_13)];
        let v_153 = &param4[(i32(_scalar_params[4]) + v_13)];
        v_21 = *v_153;
        v_154 = i32(1);
        v_155 = bitcast<u32>(v_21) > bitcast<u32>(v_154);
        if (v_155) {
            v_156 = i32(1);
            v_23 = v_21 - v_156;
            v_24 = i32(0);
            v_25 = v_24;
            v_26 = v_23;
            loop {
                v_157 = i32(0);
                v_158 = v_26 != v_157;
                if (!v_158) {
                    break;
                }
                v_159 = i32(1);
                v_133 = bitcast<i32>(bitcast<u32>(v_26) >> u32(v_159));
                v_160 = i32(1);
                v_134 = v_25 + v_160;
                v_25 = v_134;
                v_26 = v_133;
            }
            v_161 = i32(8);
            v_162 = v_25 <= v_161;
            if (v_162) {
                v_91 = bitcast<i32>(bitcast<u32>(v_18) / bitcast<u32>(v_21));
                v_92 = bitcast<i32>(bitcast<u32>(v_19) / bitcast<u32>(v_91));
                v_163 = i32(1);
                v_93 = v_92 + v_163;
                v_164 = bitcast<u32>(v_93) < bitcast<u32>(v_21);
                v_165 = i32(1);
                v_94 = v_92 + v_165;
                v_166 = select(v_21, v_94, v_164);
                v_95 = v_21 - v_166;
                v_167 = i32(1);
                v_96 = v_95 + v_167;
                v_97 = v_21 - v_96;
                v_98 = v_91 * v_97;
                v_99 = v_19 - v_98;
                v_168 = i32(0);
                v_169 = bitcast<u32>(v_95) > bitcast<u32>(v_168);
                v_170 = i32(1);
                v_100 = v_95 + v_170;
                v_101 = v_100 - v_95;
                v_102 = v_91 * v_101;
                v_103 = v_18 - v_98;
                v_104 = select(v_103, v_102, v_169);
                v_105 = v_20;
                v_106 = v_99;
                v_107 = v_104;
                v_108 = v_14;
                loop {
                    v_171 = i32(8388608);
                    v_172 = bitcast<u32>(v_107) <= bitcast<u32>(v_171);
                    if (!v_172) {
                        v_109 = v_95;
                        v_110 = v_108;
                        v_111 = v_15;
                        v_112 = v_16;
                        v_113 = v_17;
                        v_114 = v_107;
                        v_115 = v_106;
                        v_116 = v_105;
                        break;
                    }
                    v_173 = i32(8);
                    v_118 = bitcast<i32>(bitcast<u32>(v_107) << u32(v_173));
                    v_174 = bitcast<u32>(v_108) >= bitcast<u32>(v_138);
                    if (v_174) {
                        v_122 = i32(0);
                        v_123 = v_122;
                        v_124 = v_108;
                    } else {
                        v_119 = v_137 + v_108;
                        v_175 = (i32(_scalar_params[3]) + v_119);
                        v_176 = i32(((u32(atomicLoad(&param1[(u32(v_175) / 4u)])) >> ((u32(v_175) % 4u) * 8u)) & 0xFFu));
                        v_120 = i32(v_176);
                        v_177 = i32(1);
                        v_121 = v_108 + v_177;
                        v_123 = v_120;
                        v_124 = v_121;
                    }
                    v_178 = i32(8);
                    v_125 = bitcast<i32>(bitcast<u32>(v_105) << u32(v_178));
                    v_126 = v_125 | v_123;
                    v_179 = i32(1);
                    v_127 = v_126 >> u32(v_179);
                    v_180 = i32(8);
                    v_128 = bitcast<i32>(bitcast<u32>(v_106) << u32(v_180));
                    v_181 = i32(255);
                    v_129 = ~v_127;
                    v_130 = v_129 & v_181;
                    v_131 = v_128 + v_130;
                    v_182 = i32(2147483647);
                    v_132 = v_131 & v_182;
                    v_105 = v_123;
                    v_106 = v_132;
                    v_107 = v_118;
                    v_108 = v_124;
                }
            } else {
                v_183 = i32(8);
                v_27 = v_25 - v_183;
                v_184 = i32(31);
                v_28 = v_27 & v_184;
                v_29 = bitcast<i32>(bitcast<u32>(v_23) >> u32(v_28));
                v_185 = i32(1);
                v_30 = v_29 + v_185;
                v_31 = bitcast<i32>(bitcast<u32>(v_18) / bitcast<u32>(v_30));
                v_32 = bitcast<i32>(bitcast<u32>(v_19) / bitcast<u32>(v_31));
                v_186 = i32(1);
                v_33 = v_32 + v_186;
                v_187 = bitcast<u32>(v_33) < bitcast<u32>(v_30);
                v_188 = i32(1);
                v_34 = v_32 + v_188;
                v_189 = select(v_30, v_34, v_187);
                v_35 = v_30 - v_189;
                v_190 = i32(1);
                v_36 = v_35 + v_190;
                v_37 = v_30 - v_36;
                v_38 = v_31 * v_37;
                v_39 = v_19 - v_38;
                v_191 = i32(0);
                v_192 = bitcast<u32>(v_35) > bitcast<u32>(v_191);
                v_193 = i32(1);
                v_40 = v_35 + v_193;
                v_41 = v_40 - v_35;
                v_42 = v_31 * v_41;
                v_43 = v_18 - v_38;
                v_44 = select(v_43, v_42, v_192);
                v_45 = v_20;
                v_46 = v_39;
                v_47 = v_44;
                v_48 = v_14;
                loop {
                    v_194 = i32(8388608);
                    v_195 = bitcast<u32>(v_47) <= bitcast<u32>(v_194);
                    if (!v_195) {
                        break;
                    }
                    v_196 = i32(8);
                    v_76 = bitcast<i32>(bitcast<u32>(v_47) << u32(v_196));
                    v_197 = bitcast<u32>(v_48) >= bitcast<u32>(v_138);
                    if (v_197) {
                        v_80 = i32(0);
                        v_81 = v_80;
                        v_82 = v_48;
                    } else {
                        v_77 = v_137 + v_48;
                        v_198 = (i32(_scalar_params[3]) + v_77);
                        v_199 = i32(((u32(atomicLoad(&param1[(u32(v_198) / 4u)])) >> ((u32(v_198) % 4u) * 8u)) & 0xFFu));
                        v_78 = i32(v_199);
                        v_200 = i32(1);
                        v_79 = v_48 + v_200;
                        v_81 = v_78;
                        v_82 = v_79;
                    }
                    v_201 = i32(8);
                    v_83 = bitcast<i32>(bitcast<u32>(v_45) << u32(v_201));
                    v_84 = v_83 | v_81;
                    v_202 = i32(1);
                    v_85 = v_84 >> u32(v_202);
                    v_203 = i32(8);
                    v_86 = bitcast<i32>(bitcast<u32>(v_46) << u32(v_203));
                    v_204 = i32(255);
                    v_87 = ~v_85;
                    v_88 = v_87 & v_204;
                    v_89 = v_86 + v_88;
                    v_205 = i32(2147483647);
                    v_90 = v_89 & v_205;
                    v_45 = v_81;
                    v_46 = v_90;
                    v_47 = v_76;
                    v_48 = v_82;
                }
                v_206 = i32(31);
                v_49 = v_27 & v_206;
                v_50 = bitcast<i32>(bitcast<u32>(v_35) << u32(v_49));
                v_207 = v_17 >= v_27;
                if (!v_207) {
                    v_51 = v_17;
                    v_52 = v_16;
                    v_53 = v_15;
                    loop {
                        v_208 = bitcast<u32>(v_53) >= bitcast<u32>(v_138);
                        if (v_208) {
                            v_58 = i32(0);
                            v_59 = v_58;
                            v_60 = v_53;
                            v_209 = i32(31);
                            v_61 = v_51 & v_209;
                            v_62 = bitcast<i32>(bitcast<u32>(v_59) << u32(v_61));
                            v_63 = v_52 | v_62;
                            v_210 = i32(8);
                            v_64 = v_51 + v_210;
                            v_211 = i32(24);
                            v_212 = v_64 <= v_211;
                            if (!v_212) {
                                v_65 = v_64;
                                v_66 = v_63;
                                v_67 = v_60;
                                break;
                            }
                            v_51 = v_64;
                            v_52 = v_63;
                            v_53 = v_60;
                        } else {
                            v_213 = i32(1);
                            v_54 = v_53 + v_213;
                            v_55 = v_138 - v_54;
                            v_56 = v_137 + v_55;
                            v_214 = (i32(_scalar_params[3]) + v_56);
                            v_215 = i32(((u32(atomicLoad(&param1[(u32(v_214) / 4u)])) >> ((u32(v_214) % 4u) * 8u)) & 0xFFu));
                            v_57 = i32(v_215);
                            v_59 = v_57;
                            v_60 = v_54;
                        }
                    }
                } else {
                    v_65 = v_17;
                    v_66 = v_16;
                    v_67 = v_15;
                }
                v_216 = i32(1);
                v_217 = i32(31);
                v_68 = v_27 & v_217;
                v_69 = bitcast<i32>(bitcast<u32>(v_216) << u32(v_68));
                v_218 = i32(1);
                v_70 = v_69 - v_218;
                v_71 = v_66 & v_70;
                v_219 = i32(31);
                v_72 = v_27 & v_219;
                v_73 = bitcast<i32>(bitcast<u32>(v_66) >> u32(v_72));
                v_74 = v_65 - v_27;
                v_75 = v_50 | v_71;
                v_220 = bitcast<u32>(v_75) > bitcast<u32>(v_23);
                if (v_220) {
                    v_109 = v_23;
                    v_110 = v_48;
                    v_111 = v_67;
                    v_112 = v_73;
                    v_113 = v_74;
                    v_114 = v_47;
                    v_115 = v_46;
                    v_116 = v_45;
                } else {
                    v_109 = v_75;
                    v_110 = v_48;
                    v_111 = v_67;
                    v_112 = v_73;
                    v_113 = v_74;
                    v_114 = v_47;
                    v_115 = v_46;
                    v_116 = v_45;
                }
            }
        } else {
            v_22 = i32(0);
            v_109 = v_22;
            v_110 = v_14;
            v_111 = v_15;
            v_112 = v_16;
            v_113 = v_17;
            v_114 = v_18;
            v_115 = v_19;
            v_116 = v_20;
        }
        param5[(i32(_scalar_params[5]) + v_13)] = v_109;
        v_221 = i32(1);
        v_117 = v_13 + v_221;
        v_13 = v_117;
        v_14 = v_110;
        v_15 = v_111;
        v_16 = v_112;
        v_17 = v_113;
        v_18 = v_114;
        v_19 = v_115;
        v_20 = v_116;
    }
    return;
}
