// Kernel: Tests23_DecodeUintLongFormKernel
// Workgroup: 64
// SharedMem: 0B
// Bindings: 4
// Time: 2026-05-05T13:41:16.1070000Z

// Kernel: Tests23_DecodeUintLongFormKernel
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: Tests23_DecodeUintLongFormKernel_9
// WorkgroupSize: 64


// ============ F32 Special Value Helpers ============

var<private> _ilgpu_runtime_zero : u32 = 0u;
fn _f32_pos_inf() -> f32 { return bitcast<f32>(0x7F800000u | _ilgpu_runtime_zero); }
fn _f32_neg_inf() -> f32 { return bitcast<f32>(0xFF800000u | _ilgpu_runtime_zero); }
fn _f32_qnan()    -> f32 { return bitcast<f32>(0x7FC00000u | _ilgpu_runtime_zero); }

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_51 {
    field_0 : i32,
    field_1 : i32,
    field_2 : i32,
    field_3 : i32,
    field_4 : i32,
    field_5 : i32,
    field_6 : i32,
    field_7 : i32,
    field_8 : i32,
    field_9 : i32,
};

// Param 1: View<Int8, Generic> (Element: Int8)
@group(0) @binding(0) var<storage, read_write> param1 : array<atomic<u32>>;
// Param 2: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// Param 3: Int32 (Element: Int32)
// -> Packed scalar at slot 1 (1 slots, type: i32)
// Param 4: View<Int32, Generic> (Element: Int32)
@group(0) @binding(1) var<storage, read_write> param4 : array<i32>;
// Param 5: View<Int32, Generic> (Element: Int32)
@group(0) @binding(2) var<storage, read_write> param5 : array<i32>;
// Param 6: Int32 (Element: Int32)
// -> Packed scalar at slot 2 (1 slots, type: i32)
// View offset for param1 at scalar slot 3
// View offset for param4 at scalar slot 4
// View offset for param5 at scalar slot 5
@group(0) @binding(3) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

fn Tests23_ReadByte_973(p_1404 : ptr<function, struct_51>, p_1405 : ptr<storage, array<atomic<u32>>, read_write>, p_1406 : i32, p_1407 : i32) -> i32 {
    let v_0 = p_1404;
    let v_1 : ptr<storage, array<atomic<u32>>, read_write> = p_1405;
    var v_2 : i32 = p_1406;
    var v_3 : i32 = p_1407;
    var _ilgpu_return_val : i32 = 0;
    var v_5 : i32;
    var v_6 : bool;
    var v_8 : i32;
    var v_9 : i32;
    var v_11 : i32;
    var v_12 : i32;
    var v_14 : i32;
    var v_15 : i32;
    var v_16 : i32;
    var v_17 : i32;
    var v_18 : i32;
    var current_block : i32 = 0;
    loop {
        switch (current_block) {
            case 0: {
                let v_4 = &(*v_0).field_0;
                v_5 = *v_4;
                v_6 = bitcast<u32>(v_5) >= bitcast<u32>(v_3);
            }
            case 1: {
                let v_7 = &(*v_0).field_0;
                v_8 = *v_7;
                v_9 = v_2 + v_8;
                let v_10 = &v_1[v_9];
                v_11 = *v_10;
                v_12 = i32(v_11);
                let v_13 = &(*v_0).field_0;
                v_14 = *v_13;
                v_15 = i32(1);
                v_16 = v_14 + v_15;
                *v_13 = v_16;
            }
            case 2: {
                v_17 = i32(0);
            }
            case 3: {
            }
            default: { break; }
        }
        if (current_block == -1) { break; }
    }
    return _ilgpu_return_val;
}
fn Tests23_ReadByteFromEnd_971(p_1372 : ptr<function, struct_51>, p_1373 : ptr<storage, array<atomic<u32>>, read_write>, p_1374 : i32, p_1375 : i32) -> i32 {
    let v_0 = p_1372;
    let v_1 : ptr<storage, array<atomic<u32>>, read_write> = p_1373;
    var v_2 : i32 = p_1374;
    var v_3 : i32 = p_1375;
    var _ilgpu_return_val : i32 = 0;
    var v_5 : i32;
    var v_6 : bool;
    var v_8 : i32;
    var v_9 : i32;
    var v_10 : i32;
    var v_12 : i32;
    var v_13 : i32;
    var v_14 : i32;
    var v_16 : i32;
    var v_17 : i32;
    var v_18 : i32;
    var v_19 : i32;
    var current_block : i32 = 0;
    loop {
        switch (current_block) {
            case 0: {
                let v_4 = &(*v_0).field_1;
                v_5 = *v_4;
                v_6 = bitcast<u32>(v_5) >= bitcast<u32>(v_3);
            }
            case 1: {
                let v_7 = &(*v_0).field_1;
                v_8 = *v_7;
                v_9 = i32(1);
                v_10 = v_8 + v_9;
                *v_7 = v_10;
                let v_11 = &(*v_0).field_1;
                v_12 = *v_11;
                v_13 = v_3 - v_12;
                v_14 = v_2 + v_13;
                let v_15 = &v_1[v_14];
                v_16 = *v_15;
                v_17 = i32(v_16);
            }
            case 2: {
                v_18 = i32(0);
            }
            case 3: {
            }
            default: { break; }
        }
        if (current_block == -1) { break; }
    }
    return _ilgpu_return_val;
}
fn Tests23_DecodeBits_969(p_1323 : ptr<function, struct_51>, p_1324 : ptr<storage, array<atomic<u32>>, read_write>, p_1325 : i32, p_1326 : i32, p_1327 : i32) -> i32 {
    let v_0 = p_1323;
    let v_1 : ptr<storage, array<atomic<u32>>, read_write> = p_1324;
    var v_2 : i32 = p_1325;
    var v_3 : i32 = p_1326;
    var v_4 : i32 = p_1327;
    var _ilgpu_return_val : i32 = 0;
    var v_6 : i32;
    var v_8 : i32;
    var v_9 : bool;
    var v_10 : i32;
    var v_11 : i32;
    var v_12 : i32;
    var v_13 : i32;
    var v_14 : i32;
    var v_15 : i32;
    var v_16 : i32;
    var v_17 : i32;
    var v_18 : i32;
    var v_19 : i32;
    var v_20 : bool;
    var v_21 : i32;
    var v_22 : i32;
    var v_23 : i32;
    var v_24 : i32;
    var v_25 : i32;
    var v_26 : i32;
    var v_27 : i32;
    var v_28 : i32;
    var v_29 : i32;
    var v_30 : i32;
    var v_31 : i32;
    var v_32 : i32;
    var v_33 : i32;
    var v_37 : i32;
    var v_38 : i32;
    var current_block : i32 = 0;
    loop {
        switch (current_block) {
            case 0: {
                let v_5 = &(*v_0).field_2;
                v_6 = *v_5;
                let v_7 = &(*v_0).field_3;
                v_8 = *v_7;
                v_9 = v_8 >= v_4;
            }
            case 1: {
                // Call: Tests23_ReadByteFromEnd_15 (Unmapped)
                v_12 = i32(0); // Unmapped fallback
                v_13 = i32(31);
                v_14 = v_10 & v_13;
                v_15 = v_12 << u32(v_14);
                v_16 = v_11 | v_15;
                v_17 = i32(8);
                v_18 = v_10 + v_17;
                v_19 = i32(24);
                v_20 = v_18 <= v_19;
            }
            case 2: {
                v_23 = i32(1);
                v_24 = i32(31);
                v_25 = v_4 & v_24;
                v_26 = v_23 << u32(v_25);
                v_27 = i32(1);
                v_28 = v_26 - v_27;
                v_29 = v_22 & v_28;
                v_30 = i32(31);
                v_31 = v_4 & v_30;
                v_32 = v_22 >> u32(v_31);
                v_33 = v_21 - v_4;
                let v_34 = &(*v_0).field_2;
                *v_34 = v_32;
                let v_35 = &(*v_0).field_3;
                *v_35 = v_33;
                let v_36 = &(*v_0).field_4;
                v_37 = *v_36;
                v_38 = v_37 + v_4;
                *v_36 = v_38;
            }
            default: { break; }
        }
        if (current_block == -1) { break; }
    }
    return _ilgpu_return_val;
}
fn Tests23_Normalize_967(p_1268 : ptr<function, struct_51>, p_1269 : ptr<storage, array<atomic<u32>>, read_write>, p_1270 : i32, p_1271 : i32) {
    let v_0 = p_1268;
    let v_1 : ptr<storage, array<atomic<u32>>, read_write> = p_1269;
    var v_2 : i32 = p_1270;
    var v_3 : i32 = p_1271;
    var v_12 : i32;
    var v_13 : i32;
    var v_14 : bool;
    var v_15 : i32;
    var v_16 : i32;
    var v_17 : i32;
    var v_18 : i32;
    var v_19 : i32;
    var v_20 : i32;
    var v_21 : i32;
    var v_22 : i32;
    var v_23 : i32;
    var v_24 : i32;
    var v_25 : i32;
    var v_26 : i32;
    var v_27 : i32;
    var v_28 : i32;
    var v_29 : i32;
    var v_30 : i32;
    var v_31 : i32;
    var v_32 : i32;
    var v_33 : i32;
    var v_34 : i32;
    var v_35 : i32;
    var v_36 : i32;
    var v_37 : i32;
    var current_block : i32 = 0;
    loop {
        switch (current_block) {
            case 0: {
                let v_4 = &(*v_0).field_5;
                let v_5 = &(*v_0).field_4;
                let v_6 = &(*v_0).field_5;
                let v_7 = &(*v_0).field_8;
                let v_8 = &(*v_0).field_8;
                let v_9 = &(*v_0).field_8;
                let v_10 = &(*v_0).field_6;
                let v_11 = &(*v_0).field_6;
            }
            case 1: {
                v_12 = *v_4;
                v_13 = i32(8388608);
                v_14 = bitcast<u32>(v_12) <= bitcast<u32>(v_13);
            }
            case 2: {
            }
            case 3: {
                v_15 = *v_5;
                v_16 = i32(8);
                v_17 = v_15 + v_16;
                *v_5 = v_17;
                v_18 = *v_6;
                v_19 = i32(8);
                v_20 = v_18 << u32(v_19);
                *v_6 = v_20;
                v_21 = *v_7;
                // Call: Tests23_ReadByte_16 (Unmapped)
                v_22 = i32(0); // Unmapped fallback
                *v_8 = v_22;
                v_23 = i32(8);
                v_24 = v_21 << u32(v_23);
                v_25 = *v_9;
                v_26 = v_24 | v_25;
                v_27 = i32(1);
                v_28 = v_26 >> u32(v_27);
                v_29 = *v_10;
                v_30 = i32(8);
                v_31 = v_29 << u32(v_30);
                v_32 = i32(255);
                v_33 = ~v_28;
                v_34 = v_33 & v_32;
                v_35 = v_31 + v_34;
                v_36 = i32(2147483647);
                v_37 = v_35 & v_36;
                *v_11 = v_37;
            }
            default: { break; }
        }
        if (current_block == -1) { break; }
    }
    return;
}
fn Tests23_EcIlog_965(p_1251 : i32) -> i32 {
    var v_0 : i32 = p_1251;
    var _ilgpu_return_val : i32 = 0;
    var v_1 : i32;
    var v_2 : i32;
    var v_3 : i32;
    var v_4 : i32;
    var v_5 : bool;
    var v_6 : i32;
    var v_7 : i32;
    var v_8 : i32;
    var v_9 : i32;
    var current_block : i32 = 0;
    loop {
        switch (current_block) {
            case 0: {
                v_1 = i32(0);
            }
            case 1: {
                v_4 = i32(0);
                v_5 = v_3 != v_4;
            }
            case 2: {
            }
            case 3: {
                v_6 = i32(1);
                v_7 = v_3 >> u32(v_6);
                v_8 = i32(1);
                v_9 = v_2 + v_8;
            }
            default: { break; }
        }
        if (current_block == -1) { break; }
    }
    return _ilgpu_return_val;
}
fn Tests23_DecodeUint_963(p_1093 : ptr<function, struct_51>, p_1094 : ptr<storage, array<atomic<u32>>, read_write>, p_1095 : i32, p_1096 : i32, p_1097 : i32) -> i32 {
    let v_0 = p_1093;
    let v_1 : ptr<storage, array<atomic<u32>>, read_write> = p_1094;
    var v_2 : i32 = p_1095;
    var v_3 : i32 = p_1096;
    var v_4 : i32 = p_1097;
    var _ilgpu_return_val : i32 = 0;
    var v_5 : i32;
    var v_6 : bool;
    var v_7 : i32;
    var v_9 : i32;
    var v_10 : i32;
    var v_11 : i32;
    var v_12 : i32;
    var v_13 : i32;
    var v_14 : bool;
    var v_15 : i32;
    var v_16 : i32;
    var v_17 : i32;
    var v_18 : i32;
    var v_19 : i32;
    var v_20 : i32;
    var v_21 : i32;
    var v_23 : i32;
    var v_24 : i32;
    var v_27 : i32;
    var v_29 : i32;
    var v_30 : i32;
    var v_31 : i32;
    var v_32 : i32;
    var v_33 : bool;
    var v_34 : i32;
    var v_35 : i32;
    var v_36 : i32;
    var v_37 : i32;
    var v_39 : i32;
    var v_40 : i32;
    var v_41 : i32;
    var v_42 : i32;
    var v_43 : i32;
    var v_45 : i32;
    var v_46 : i32;
    var v_47 : i32;
    var v_48 : bool;
    var v_50 : i32;
    var v_51 : i32;
    var v_53 : i32;
    var v_54 : i32;
    var v_55 : i32;
    var v_56 : i32;
    var v_57 : i32;
    var v_58 : i32;
    var v_60 : void;
    var v_61 : i32;
    var v_62 : i32;
    var v_63 : i32;
    var v_64 : i32;
    var v_65 : i32;
    var v_66 : bool;
    var v_67 : i32;
    var v_70 : i32;
    var v_71 : i32;
    var v_74 : i32;
    var v_76 : i32;
    var v_77 : i32;
    var v_78 : i32;
    var v_79 : i32;
    var v_80 : bool;
    var v_81 : i32;
    var v_82 : i32;
    var v_83 : i32;
    var v_84 : i32;
    var v_86 : i32;
    var v_87 : i32;
    var v_88 : i32;
    var v_89 : i32;
    var v_90 : i32;
    var v_92 : i32;
    var v_93 : i32;
    var v_94 : i32;
    var v_95 : bool;
    var v_97 : i32;
    var v_98 : i32;
    var v_100 : i32;
    var v_101 : i32;
    var v_102 : i32;
    var v_103 : i32;
    var v_104 : i32;
    var v_105 : i32;
    var v_107 : void;
    var v_108 : i32;
    var current_block : i32 = 0;
    loop {
        switch (current_block) {
            case 0: {
                v_5 = i32(1);
                v_6 = bitcast<u32>(v_4) > bitcast<u32>(v_5);
            }
            case 1: {
                v_7 = i32(1);
                let v_8 = &(*v_0).field_9;
                *v_8 = v_7;
                v_9 = i32(0);
            }
            case 2: {
                v_10 = i32(1);
                v_11 = v_4 - v_10;
                // Call: Tests23_EcIlog_12 (Unmapped)
                v_12 = i32(0); // Unmapped fallback
                v_13 = i32(8);
                v_14 = v_12 <= v_13;
            }
            case 3: {
                v_15 = i32(8);
                v_16 = v_12 - v_15;
                v_17 = i32(31);
                v_18 = v_16 & v_17;
                v_19 = v_11 >> u32(v_18);
                v_20 = i32(1);
                v_21 = v_19 + v_20;
                let v_22 = &(*v_0).field_5;
                v_23 = *v_22;
                v_24 = v_23 / v_21;
                let v_25 = &(*v_0).field_7;
                *v_25 = v_24;
                let v_26 = &(*v_0).field_6;
                v_27 = *v_26;
                let v_28 = &(*v_0).field_7;
                v_29 = *v_28;
                v_30 = v_27 / v_29;
                v_31 = i32(1);
                v_32 = v_30 + v_31;
                v_33 = bitcast<u32>(v_32) < bitcast<u32>(v_21);
                v_34 = i32(1);
                v_35 = v_30 + v_34;
                v_36 = select(v_21, v_35, v_33);
                v_37 = v_21 - v_36;
                let v_38 = &(*v_0).field_7;
                v_39 = *v_38;
                v_40 = i32(1);
                v_41 = v_37 + v_40;
                v_42 = v_21 - v_41;
                v_43 = v_39 * v_42;
                let v_44 = &(*v_0).field_6;
                v_45 = *v_44;
                v_46 = v_45 - v_43;
                *v_44 = v_46;
                v_47 = i32(0);
                v_48 = bitcast<u32>(v_37) > bitcast<u32>(v_47);
            }
            case 4: {
                let v_49 = &(*v_0).field_5;
                v_50 = *v_49;
                v_51 = v_50 - v_43;
            }
            case 5: {
                let v_52 = &(*v_0).field_7;
                v_53 = *v_52;
                v_54 = i32(1);
                v_55 = v_37 + v_54;
                v_56 = v_55 - v_37;
                v_57 = v_53 * v_56;
            }
            case 6: {
                let v_59 = &(*v_0).field_5;
                *v_59 = v_58;
                // Call: Tests23_Normalize_13 (Unmapped)
                v_60 = void(0); // Unmapped fallback
                v_61 = i32(31);
                v_62 = v_16 & v_61;
                v_63 = v_37 << u32(v_62);
                // Call: Tests23_DecodeBits_14 (Unmapped)
                v_64 = i32(0); // Unmapped fallback
                v_65 = v_63 | v_64;
                v_66 = bitcast<u32>(v_65) > bitcast<u32>(v_11);
            }
            case 7: {
            }
            case 8: {
                v_67 = i32(1);
                let v_68 = &(*v_0).field_9;
                *v_68 = v_67;
            }
            case 9: {
                let v_69 = &(*v_0).field_5;
                v_70 = *v_69;
                v_71 = v_70 / v_4;
                let v_72 = &(*v_0).field_7;
                *v_72 = v_71;
                let v_73 = &(*v_0).field_6;
                v_74 = *v_73;
                let v_75 = &(*v_0).field_7;
                v_76 = *v_75;
                v_77 = v_74 / v_76;
                v_78 = i32(1);
                v_79 = v_77 + v_78;
                v_80 = bitcast<u32>(v_79) < bitcast<u32>(v_4);
                v_81 = i32(1);
                v_82 = v_77 + v_81;
                v_83 = select(v_4, v_82, v_80);
                v_84 = v_4 - v_83;
                let v_85 = &(*v_0).field_7;
                v_86 = *v_85;
                v_87 = i32(1);
                v_88 = v_84 + v_87;
                v_89 = v_4 - v_88;
                v_90 = v_86 * v_89;
                let v_91 = &(*v_0).field_6;
                v_92 = *v_91;
                v_93 = v_92 - v_90;
                *v_91 = v_93;
                v_94 = i32(0);
                v_95 = bitcast<u32>(v_84) > bitcast<u32>(v_94);
            }
            case 10: {
                let v_96 = &(*v_0).field_5;
                v_97 = *v_96;
                v_98 = v_97 - v_90;
            }
            case 11: {
                let v_99 = &(*v_0).field_7;
                v_100 = *v_99;
                v_101 = i32(1);
                v_102 = v_84 + v_101;
                v_103 = v_102 - v_84;
                v_104 = v_100 * v_103;
            }
            case 12: {
                let v_106 = &(*v_0).field_5;
                *v_106 = v_105;
                // Call: Tests23_Normalize_13 (Unmapped)
                v_107 = void(0); // Unmapped fallback
            }
            case 13: {
            }
            default: { break; }
        }
        if (current_block == -1) { break; }
    }
    return _ilgpu_return_val;
}
fn Tests23_OpusInit_961(p_1027 : ptr<storage, array<atomic<u32>>, read_write>, p_1028 : i32, p_1029 : i32) -> struct_51 {
    let v_0 : ptr<storage, array<atomic<u32>>, read_write> = p_1027;
    var v_1 : i32 = p_1028;
    var v_2 : i32 = p_1029;
    var v_3 : struct_51;
    var v_4 : i32;
    v_4 = i32(0);
    var v_5 : i32;
    v_5 = i32(0);
    var v_6 : i32;
    v_6 = i32(0);
    var v_7 : i32;
    v_7 = i32(0);
    var v_8 : i32;
    v_8 = i32(0);
    var v_9 : i32;
    v_9 = i32(0);
    var v_10 : i32;
    v_10 = i32(0);
    var v_11 : i32;
    v_11 = i32(0);
    var v_12 : i32;
    v_12 = i32(0);
    var v_13 : i32;
    v_13 = i32(0);
    var v_14 : struct_51;
    v_14 = struct_51(v_4, v_5, v_6, v_7, v_8, v_9, v_10, v_11, v_12, v_13);
    v_3 = v_14;
    var v_15 : i32;
    v_15 = i32(0);
    var v_16 : i32;
    v_16 = i32(0);
    var v_17 : i32;
    v_17 = i32(0);
    var v_18 : i32;
    v_18 = i32(0);
    var v_19 : i32;
    v_19 = i32(9);
    var v_20 : i32;
    v_20 = i32(-1);
    var v_21 : i32;
    v_21 = i32(0);
    var v_22 : i32;
    v_22 = i32(0);
    var v_23 : i32;
    v_23 = i32(0);
    var v_24 : i32;
    v_24 = i32(0);
    var v_25 : struct_51;
    v_25 = struct_51(v_15, v_16, v_17, v_18, v_19, v_21, v_22, v_23, v_20, v_24);
    v_3 = v_25;
    let v_26 = v_3; // addrSpaceCast
    var v_27 : i32;
    // Call: Tests23_ReadByte_16 (Unmapped)
    v_27 = i32(0); // Unmapped fallback
    let v_28 = &v_3.field_8;
    *v_28 = v_27;
    var v_29 : i32;
    v_29 = i32(2);
    let v_30 = &v_3.field_5;
    *v_30 = v_29;
    var v_31 : struct_51;
    v_31 = v_3;
    var v_32 : i32;
    v_32 = v_31.field_5;
    var v_33 : i32;
    v_33 = i32(1);
    var v_34 : i32;
    v_34 = v_32 - v_33;
    var v_35 : struct_51;
    v_35 = v_3;
    var v_36 : i32;
    v_36 = v_35.field_8;
    var v_37 : i32;
    v_37 = i32(1);
    var v_38 : i32;
    v_38 = v_36 >> u32(v_37);
    var v_39 : i32;
    v_39 = v_34 - v_38;
    let v_40 = &v_3.field_6;
    *v_40 = v_39;
    let v_41 = &v_3.field_5;
    var v_42 : i32;
    v_42 = *v_41;
    var v_43 : i32;
    v_43 = i32(8);
    var v_44 : i32;
    v_44 = v_42 << u32(v_43);
    *v_41 = v_44;
    var v_45 : struct_51;
    v_45 = v_3;
    var v_46 : i32;
    v_46 = v_45.field_0;
    var v_47 : i32;
    v_47 = v_45.field_1;
    var v_48 : i32;
    v_48 = v_45.field_2;
    var v_49 : i32;
    v_49 = v_45.field_3;
    var v_50 : i32;
    v_50 = v_45.field_4;
    var v_51 : i32;
    v_51 = v_45.field_5;
    var v_52 : i32;
    v_52 = v_45.field_6;
    var v_53 : i32;
    v_53 = v_45.field_7;
    var v_54 : i32;
    v_54 = v_45.field_8;
    var v_55 : i32;
    v_55 = v_45.field_9;
    var v_56 : struct_51;
    v_56 = struct_51(v_46, v_47, v_48, v_49, v_50, v_51, v_52, v_53, v_54, v_55);
    return v_56;
}
@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;
    // Seed the runtime-zero used by F32 special-value helpers from a
    // @builtin value so Naga's const-evaluator cannot fold it. Required
    // because `bitcast<f32>(const_u32_with_inf_bit_pattern)` is rejected
    // at shader creation. See WGSLEmulationLibrary.F32SpecialValueFunctions.
    _ilgpu_runtime_zero = local_id.x ^ local_id.x;

    var v_0 : i32 = 0;
    var v_1 : i32 = 0;
    var v_2 : i32 = 0;
    var v_3 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_3) >= _ilgpu_user_dim) { return; }
    var v_5 = bitcast<i32>(_scalar_params[0]);
    var v_6 = bitcast<i32>(_scalar_params[1]);
    let v_7 = &param4;
    let v_8 = &param5;
    var v_9 = bitcast<i32>(_scalar_params[2]);
    var v_10 : struct_51;
    var v_11 : i32;
    var v_12 : i32;
    var v_13 : i32;
    var v_14 : i32;
    var v_15 : i32;
    var v_16 : i32;
    var v_17 : i32;
    var v_18 : i32;
    var v_19 : i32;
    var v_20 : i32;
    var v_21 : struct_51;
    var v_22 : struct_51;
    var v_33 : struct_51;
    var v_37 : i32;
    var v_38 : i32;
    var v_39 : i32;
    var v_23 : i32;
    var v_24 : i32;
    var v_25 : i32;
    var v_26 : i32;
    var v_27 : i32;
    var v_28 : i32;
    var v_29 : i32;
    var v_30 : i32;
    var v_31 : i32;
    var v_32 : i32;
    var v_34 : bool;











    v_11 = i32(0);
    v_12 = i32(0);
    v_13 = i32(0);
    v_14 = i32(0);
    v_15 = i32(0);
    v_16 = i32(0);
    v_17 = i32(0);
    v_18 = i32(0);
    v_19 = i32(0);
    v_20 = i32(0);
    v_21 = struct_51(v_11, v_12, v_13, v_14, v_15, v_16, v_17, v_18, v_19, v_20);
    v_10 = v_21;
    v_22 = Tests23_OpusInit_961(v_4, v_5, v_6);
    v_23 = v_22.field_0;
    v_24 = v_22.field_1;
    v_25 = v_22.field_2;
    v_26 = v_22.field_3;
    v_27 = v_22.field_4;
    v_28 = v_22.field_5;
    v_29 = v_22.field_6;
    v_30 = v_22.field_7;
    v_31 = v_22.field_8;
    v_32 = v_22.field_9;
    v_33 = struct_51(v_23, v_24, v_25, v_26, v_27, v_28, v_29, v_30, v_31, v_32);
    v_10 = v_33;
    v_0 = i32(0);
    v_1 = v_0;
    loop {
        v_34 = v_1 < v_9;
        if (!v_34) {
            break;
        }
        let v_35 = &param5[(i32(_scalar_params[5]) + v_1)];
        let v_36 = &param4[(i32(_scalar_params[4]) + v_1)];
        v_37 = *v_36;
        v_38 = Tests23_DecodeUint_963(&v_10, v_4, v_5, v_6, v_37);
        *v_35 = v_38;
        v_39 = i32(1);
        v_2 = v_1 + v_39;
        v_1 = v_2;
    }
    return;
}
